### ISSUE TITLE
Suggestion Request (Per World Tax)

### ISSUE THREAD

**Issue by kiritodragneel** [TownyAdvanced/Towny#2538]
Idea: So you would add this one of two ways i can see ether with a permission node looking like 
- Towny.Tax.64 and this would set the daily tax to 64 for example or via a config option like so 

WorldTax 
  World1: 64
  World2: 230
  World 3: 453

Both options seem as good as each other. 

I Think it could also be cool if you added or changed the config system, so it would make a simple global config which would have an option inside saying 

PerWorldTowny: true/false 

This would then enable it so if true each world would be loaded into a folder of its own with a copy of the current config and would make it so that world would follow the config of its corosponding folder.

**Comment by LlmDl** [comment]
This ticket is being closed, it is something that is probably never going to be accomplished because Towns can exist in two or more worlds at the same time. Also going through the entire codebase and changing settings-look-ups from what it is now, to one that handles different worlds would also be a nightmare.

That being said, the API would allow someone to make their own tax system that ran instead of Towny's. This would still require you to limit towns to one world though.
