### ISSUE TITLE
Suggestion: Towny Mandate mechanic

### ISSUE THREAD

**Issue by Senre-MC** [TownyAdvanced/Towny#2777]
I notice the main issue with towny's nations is the fact that it lacks the most important rule to define a nation: A nation must _own_ their towns. Rather than being viewed as though a fully fledged country, or even a faction, most people see it as claim power and nothing more. I propose a way that rule can be fixed, and hopefully give nations much more meaning.

Nations can mandate their territory starting with their core cities. The way a town becomes considered a core of the nation is through /t set mandate. Yes, the mayor will have to do it instead of the leader. The cons of becoming mandated is that you will be completely locked in the nation. You won't be able to /n leave.

To balance this con with a pro, you will be able to challenge the mandate that locks your town with /n rebel (rebel faction name). This will make your town become rebellious, and in the position to break the country.

Say, **/n Galactic_Republic** has been abusing the mandate mechanic by turning back on their mandated cities, and they are sick of being controlled. The towns then proceed to type **/n rebel CoIS**, and then the faction is then inside of the republic with /t Geneosis as the faction's stronghold (as they typed the command first).

A mandate score could be added so that nations won't be able to take over the next 7 maps, and spam beg towns to /t set mandate (at least not easily). Mandate score is added over time, and is also worked for, this could take the form of something such as the individual servers rewarding the nation for tasks in their cities. Whenever a city is taken in, they have to spend the mandate score. The lower the mandate score, the weaker the nation's power over their cities are. Rebel factions would reduce the nation's mandate by, say 4 points for every city under a rebel banner. After the mandate reaches 0 points, the country is broken, and each faction becomes their own country

Whether this rebellion should have a fully fledged warday when they want to fight to make their own countries, or if the mandate score mechanic gets used instead, I'll let the developer play with the idea

**Comment by Wextra** [comment]
Tails rocks!

**Comment by LlmDl** [comment]
Interesting concept, I have a few questions:

What does "nations won't be able to take over the next 7 maps" mean?

Would one town be worth one mandate point? Either for or against the mandate? Do town populations have an effect on this point total? Do higher-population towns deserve more points?

My initial reaction to this is that the system should probably be enforced on all nations/towns by the admin and not require towns to side with their nation, as the towns have already chosen their nation already. Perhaps a config setting turning on the system would be best, instead of leaving it in the mayors hands. Doing so could still allow mayors to leave their nation whenever they want, but they could choose to rebel if they wanted to supplant control of the nation from the capital?

Very interesting idea, it reminds me of unhappy cities and their effects in Civilization 5.

**Comment by Wextra** [comment]
If a town is a mandate of another nation, is it possible to conquer it through war or something?

**Comment by MilesAmadeusPrower** [comment]
@LlmDl "nations won't be able to take over the next 7 maps" was a hyperbole. I meant they won't get to spam invite towns like mad and be able to lock them all in at once

As for mandating towns, I was thinking that the cost could vary based on territory (rounded by 5)

As for why I wanted to make mandating a city optional after taking them into the nation, that is based on mechanics and concepts such as in EU4 where some territories that were recently conquered aren't technically part of the said nation that occupies them. The nation would have to work to make them a proper core. The other reason behind my wanting the mayor to establish themselves, it's because it's something the king could otherwise abuse. If the mayor establishes they're part of the nation's mandate, then they will have sworn an allegiance they know they cannot easily turn back on.

Imagine a case like this: Someone from Nation A wants to colonize, so they dispatch someone to make it. Nation B antagonistically spam invites the town, making them join. Nation B instantly declares the town as mandated territory while it was meant for Nation A in the first place, making a land dispute in which Nation B would have to remove the city. However, Nation B could stay antagonistic and try to force them in as long as possible, hoping the according separtist faction doesn't break the country and they give up.

They could still win the conflict, though it took way longer than if they undo Nation B's joining, join Nation A, and then swear allegiance, declaring themselves mandated territory

**Comment by Bezod** [comment]
I like this idea, it would make conflicts more diversified and interesting.

**Comment by KarlOfDuty** [comment]
I like the idea but I think mandate is the wrong word as I feel it has lots of different non-territory related meanings especially to a non-native english speaker. I think vassal and vassalize sounds much better and still fits the kingdom themes of the plugin.

**Comment by LlmDl** [comment]
@Articdive and I were talking about this ticket and a vassal system. 

Typically a vassal comes via conquering another. Perhaps some of this ticket's ideas could be satisfied by bringing an optional vassal system into Towny war. 

A rough idea of how it could play out could be as follows:

- Nation Antelope consists of 3 towns: Athens (capital), Antwerp and Atlanta.
- Nation Badger consists of 3 towns: Brixton (capital), Babylon and Bangkok.
- The two nations are enemies and after having a war event, the Nation of Badger lost.
  - Here is where I see a few possible scenarios play out.
  1) Scenario One: Complete Nation Disbandment.
     - The Nation of Badger is disbanded and the 3 towns become Vassals of Nation Antelope.
  2) Scenario Two: Nation Badger loses all but its capital town.
     - The Nation of Badger is left with its capital town and Babylon and Bangkok become Vassals of Nation Antelope.
  3) Scernario Three: Only fallen towns in the war become Vassals
     - The Nation of Badger is left with only Babylon (which did not get removed from play in the war Event.)
     - Babylon becomes the new capital of Badger and Bangkok and Brixton both become Vassals of Antelope.
- Vassal towns of a nation could be penalized with an additional tax to their new Host Nation. 
- Vassals lose their vassal status after a period of time (15 days?) configured in the config.yml.
- After losing their vassal status the town can leave their host nation at will and join back up with the Nation of Badger.
- Optionally a vassal can renounce their old nation fully and adopt nearly full status with their new Host Nation (a pledge command could/would replace the OP's /t mandate command here.)
- Pledged nations may not leave the host Nation for double the time set for loss-of-vassal status, but they do not pay the additional tax.

**Comment by LlmDl** [comment]
So as of today's commit: https://github.com/TownyAdvanced/Towny/commit/537d8aa05c709c2d36d3660166459eb2a10113c8 it is possible to have towns that fall in EventWar become vassal towns to the conquering nation. There is a configurable number of days that they are forced to stay in the nation.
