### ISSUE TITLE
Suggestion: Format more cases of Town and Nation names in messages, to parse out the "_"

### ISSUE THREAD

**Issue by Leomixer17** [TownyAdvanced/Towny#2872]
In some cases _ are not replaced with spaces in town and nation names

### What steps will reproduce the problem?
1. Execute actions like creating a town or a nation with _ in them names and you will see _ in messages instead of spaces

Command list:
- [x] /t new
- [x] /n new
- [x] /t list
- [x] /n list
- [x] /n leave

### What is your Towny version?
0.92.0.10

### What is your spigot/craftbukkit version?
1.12.2

**Comment by LlmDl** [comment]
This would required going through just about every message sent to players that has town.getName() or nation.getName() and replacing it with the formatted versions. 

If you want to compile a list of commands you'd like to see this changed in and submit it I'll find the time to get it cleared up for you. Otherwise, the name of the town or nation does technically have "_" instead of " ".

**Comment by LlmDl** [comment]
Leaving this open another 14 days, if no list of commands is present this will be closed.

**Comment by creatorfromhell** [comment]
I think this would be better as a configuration option of some sort.

**Comment by LlmDl** [comment]
It probably would, I still don't have the time to find every instance of where we aren't formatting it out on my own. The actual config option would be very easy to add though, it should probably have it's own ticket for if/when this one is closed.

**Comment by LlmDl** [comment]
Closing until a list of places where these changes are required is presented.

**Comment by Leomixer17** [comment]
@LlmDl I've added a list of the commands having this issue that I've found

**Comment by LlmDl** [comment]
https://github.com/TownyAdvanced/Towny/commit/1d93d79a7fb6cbb3c2c1dcdabad30e065572d599

Will be a part of 0.94.0.5
