### ISSUE TITLE
Properly handle NPC accounts, war chest accounts, closed economy accounts

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#2885]
Various economy accounts can be logged into which leave bank accounts vulnerable to griefing. We should not let players log into NPC, war chest, and closed economy accounts to protect their bank values.

**Comment by AIphaDragon** [comment]
The problem is solved easily. There is already a ready solution. We tested everything. Works as you need. Link: https://www.spigotmc.org/resources/townyfix.47748/

**Comment by Articdive** [comment]
As research has shown this is a problem regarding Essentials, pretty much every plugin runs Essentials, our only option is to contact Essentials about the problem but it doesn't look like drtshock will care, the other option is to contact Vault to remove Essentials as a main economy holder, but that won't do the trick since MilkBowl doesn't really work on Vault anymore

**Comment by LlmDl** [comment]
Towny now handles these accounts properly and tells all ops/admins which IP address to ban.
