### ISSUE TITLE
Suggestion: Towny external ranks

### ISSUE THREAD

**Issue by Husnaain** [TownyAdvanced/Towny#2944]
Hi i want to suggest a new feature in the towny plugin that are the external ranks.
What we do with external ranks?
The external ranks are like normal ranks but we can give it only to other cities members with the command /t external rank add (builder/assistant/deputymayor etc.) playername
This addition would be very useful because other city members can help other towns without leaving their towns or giving hundreds of plots as embassy.

**Comment by Husnaain** [comment]
No, it should be a different thing this way you can give external ranks also to people that aren't in your nation

**Comment by LlmDl** [comment]
There's no permission node which would allow build/destroy/switch/itemuse in a town that the player doesn't already belong to, which doesn't give the player access to all other towns. Since ranks are based on permissions I don't see this as being possible without also changing how we handle a lot of other things, the largest being how we handle the player cache.
