### ISSUE TITLE
Suggestion: Better towny feedback and error messages

### ISSUE THREAD

**Issue by Bezod** [TownyAdvanced/Towny#2983]
I'd like to suggest better towny feedback/error messages after running commands in order to improve user experience.

- [x] "/t new" - not enough funds
- [x] "/n new" - not enough funds
Current error message: You can't afford to settle a new town here
Suggested error message: You can't afford to settle a new town costing [amount].

- [x] "/t new The Empire" - using spaces in town name
Current error message: The resident 'the' is not registered
Suggested error message: You can not use spaces in town names, created town TheEmpire instead

- [x] "/t claim" - not enough money in town bank. Same for nation and other town expenses.
Current error message: You cannot afford to claim 1 town blocks costing [amount]
Suggested error message: Your town can not afford this action, make sure to deposit [amount] using /t deposit [amount]

- [x] "/ta town [a] rename [b]"
Current message: none
Suggested message: Town [a] has successfully changed name to [b]

**Comment by LlmDl** [comment]
I'll be testing the /ta rename thing because I'm quite certain I fixed that a little while ago.

The naming towns with spaces is something that happens because anything more than one "word" is interpreted as the admin command '/t new name mayor' which has caused nothing but trouble. I will likely remove the admin command and move it to /ta (where I think it already exists.) After that I will make it either not accept any name with a space in it (ie: longer than one "word",) or auto-parse spaces into underscores.

**Comment by LlmDl** [comment]
All of this is a thing as of 0.92.0.13
```
    - Made feedback from /plot|town|nation|townyworld|townyadmin toggle commands translatable, ex: enabled, disabled, forced, adjustable. 
    - Made error feedback from lack for funds for /t new, /n new and /t claim much clearer.
    - Removed command: /t new NAME MAYOR
      - This used to be usable only by admins and caused lots of confusion when players would try to make towns with spaces in the name.
    - New Command: /ta town new [name] [mayor]
      - Creates a town for the mayor where the command sender is standing.
    - New Command behaviour: /t new name with spaces
      - Use of the /t new command no longer requires the use of _'s where spaces would be.
      - If a user enters spaces then they will be parsed into _'s and the town will be created.
```

**Comment by Bezod** [comment]
Thanks!!
