### ISSUE TITLE
Suggestion: Automatically delete the towns that does not have homeblock and spawn data in MySQL

### ISSUE THREAD

**Issue by ipozow** [TownyAdvanced/Towny#2992]
For some time I am getting problems with safe mode. I don't report anything because I can't reproduce this myself. 
But since 0.92.0.11 there are some problems with towns, and for all the towns the problem is the same: 
The home block and spawn tables are in blank. 

So my suggestion is when Towny founds that there is an error with a town, Towny should check if there are info in homeblock and spawn, and if there are nothing, delete it. 
It should be only for MySQL

**Comment by LlmDl** [comment]
We don't usually adopt policies of deleting data when the cause behind the problem is unknown. Towns can remove their spawn and homeblock using commands in game. I'm not saying that's what happened on your server but it can be done by players and I'm sure they wouldn't be expecting their town to be deleted.
