### ISSUE TITLE
Towny time based features slow down when the server is running at low tps

### ISSUE THREAD

**Issue by KarlOfDuty** [TownyAdvanced/Towny#2993]
This was last attempted in  0.92.0.0 1.12.2 about three months ago.

The war countdown and the time players have to stand in a plot to capture it during war gets longer when the tps is lower. We had around 150 players on for a war and this meant the tps was down between 5-10 making the time to capture plots 2-4 times longer.

**Comment by LlmDl** [comment]
I don't know if there's anything that can be done about this. That might be the nature of low ticks per second.

**Comment by KarlOfDuty** [comment]
Are there not time functions that get time irrelevant of tickrates?

**Comment by LlmDl** [comment]
Yes but we'd still have to use a task to go back and check if enough time had passed. Same end result.

**Comment by LlmDl** [comment]
I took a look at this tonight I found we are already using async tasks for the war timer. Short of re-coding it to use system time for everything this issue is still a bit dead in the water. This doesn't necessarily mean that it will be any less laggy, because we would only be look for the system time on a time-frame which is still lagging, it might stop compounding laggy time loss though.

Note to my future-self: Recode war timer to check for system time everywhere.
