### ISSUE TITLE
Suggestion: All Nation Build permission node

### ISSUE THREAD

**Issue by villed3** [TownyAdvanced/Towny#3037]
The idea is simple: allowing certain members of a nation to build on any nation plot (preferably townowned , but maybe also alltown) with just a rank. Currently, the only way to allow other nation members to build in your town is by turning the town permissions to "ally," which allows EVERYONE in EVERY town of the nation to build or destroy - except your own town members comically enough.

If this already is a feature please enlighten me with the solution.

**Comment by LlmDl** [comment]
This is something that was shot down in the past because it would be adding another permission check to the towny PlayerCache system. It would be the (I think) 4th permission check done every time a player's cache needs to be redone, which happens any time a player switches plots and tries to break/build/switch/itemuse. I'm going to keep this open in case we choose to implement it and try and find a way for it to not affect servers that opt not to use it.
