### ISSUE TITLE
ConcurrentModificationException on startup.

### ISSUE THREAD

**Issue by KevinNovak** [TownyAdvanced/Towny#3051]
### What steps will reproduce the problem?
Start server. Error occurs ~50% of the time, without changing anything about the server. When the error does occur Towny appears to be working normally.

### What is the expected output?
No error in console.

### What is your Towny version?
Towny v0.93.0.0

### What is your spigot/craftbukkit version?
Spigot 1.13.1 (git-Spigot-f6a273b-1cf8b5d)

### Please use Pastebin.com to link the following files:
1. Your full server startup from the logs\latest.log: https://pastebin.com/raw/XWdT7vwW
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/raw/TXMHar00
3. Your townyperms.yml: https://pastebin.com/raw/Gwf8P5As
4. Your log's error: https://pastebin.com/raw/fAMqq4kY

**Comment by Articdive** [comment]
This is most likely not a towny issue sinch there is no real HashMap that we are using in that case, it's an error caused by Bukkit which has most likely already been fixed at this point, or some other plugin you use changes Bukkit's permission system by overriding it. I've also not been able to reproduce this
