### ISSUE TITLE
Towny Chat is not working

### ISSUE THREAD

**Issue by Merandrei** [TownyAdvanced/Towny#3137]
### What steps will reproduce the problem?
TownyChat is not working. It may be a common problem, but I don t know what to do. I ve installed everything from your website.
![2018-12-28_13 31 46](https://user-images.githubusercontent.com/46220453/50514150-0ddd4f80-0aa5-11e9-9796-8da69f7714cf.png)

### What is the expected output?
Townychat to work. And if it s possible, it would awesome if you d tell me if it s possible to set a groupmanager (or towny) prefix as a default for every rank. For example, I would want nomads to have the Nomad rank, Assistants to have the assistant rank, and residents to have their own prefixes in chat, just like the mayor. And is it possible to set a default chat message color for ranks? I would want admins to always have their messages wrote with a color.

### What is your Towny version?
Towny Advanced 0.93.0.0 [CB/Spigot 1.11-1.13] 

### What is your spigot/craftbukkit version?
CraftBukkit version git-Spigot-fe3ab0d-162bda9 (MC: 1.13)
(Spigot 1.13)

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : [https://pastebin.com/wJuRvaGM](https://pastebin.com/wJuRvaGM)
2. Your Towny config.yml (if using MySQL please remove password,) : [https://pastebin.com/07cwd1Qq](https://pastebin.com/07cwd1Qq)
3. Your townyperms.yml : [https://pastebin.com/X61c987w](https://pastebin.com/X61c987w)
4. Your log's error : I don t know where is that

(optional) If this is to do with permissions, 
5. Your permissions file : [https://pastebin.com/WfMtqfL0](https://pastebin.com/WfMtqfL0)

(optional) If this is to do with chat,
6. Your chatconfig.yml : [https://pastebin.com/UpGhLCKi](https://pastebin.com/UpGhLCKi)
7. Your channels.yml : [https://pastebin.com/x4qn336C](https://pastebin.com/x4qn336C)

Thank you and sorry for asking that.

**Comment by LlmDl** [comment]
From the startup:
```[13:39:01] [Server thread/INFO]: [TownyChat] Enabling TownyChat v0.53
[13:39:01] [Server thread/ERROR]: [TownyChat] Failed to load Channels.yml!
[13:39:01] [Server thread/ERROR]: [TownyChat] Please check that the file passes a YAML Parser test:
[13:39:01] [Server thread/ERROR]: [TownyChat] Online YAML Parser: https://yaml-online-parser.appspot.com/
[13:39:01] [Server thread/ERROR]: [TownyChat] Could not schedule onLoadedTask.
[13:39:01] [Server thread/ERROR]: [TownyChat] Disabling TownyChat...
[13:39:01] [Server thread/INFO]: [TownyChat] Disabling TownyChat v0.53```
I ran your channels.yml through the YAML parser and it doesn't show anything wrong. Maybe double-check your file on your server in the parser.

As for having the Towny ranks all have prefixes, we don't have anything set up for that because players can have multiple ranks once they become a resident. The chatconfig.yml does show there are {permprefix} and {permsuffix} chattags, that will pull the prefix/suffix assigned in your GroupManager.

Some servers that want coloured chat have put the colour code as the rank suffix, then in the Towny chatconfig.yml, they replace {msgcolor} with {permsuffix} in the channel_formats section.

Again, not sure why your townychat isn't starting up, but if all else fails you can delete your channels.yml and chatconfig.yml and TownyChat will make new ones.

**Comment by Merandrei** [comment]
You re right. That was the problem, but I resolved it now. Thank you.
