### ISSUE TITLE
Suggestion: Height permission

### ISSUE THREAD

**Issue by magicmwin** [TownyAdvanced/Towny#3166]
Is it possible to update the plugin to be able to set permissions depending on height of the claim? I mean there are claims 16x16x256. Is it possible to be able to set permissions of whole 16x16x256 AND parts of it, say 16x16x16?

Example, I make a dwarven city, and want people to be able to buy plots overland, while deepest underground is for the town owner to make a mine, metro, etc. 

In result, if you are a common citizen, you are able to build for example on heights from 64 to 256, cause first 4 cuboids of 16x16x16 on heights 0 to 64 are restricted.

**Comment by LlmDl** [comment]
This has been shot down in the past because of how Towny's playercache works. We only have to check each similar action once per-plot, per-player (usually, there are other things that refresh the cache earlier.)

Throwing in a further checks when they cross a height means re-caching and also checking players' upwards and downwards movements.

A long while ago we'd toyed with a Mine plot though, where it would behave like a Wilds plot type but only under a certain height (so the town's surface would be unusable.) I believe it was never implemented by the previous developers because of how it would affect the cache.
