### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by BeeRando** [TownyAdvanced/Towny#3201]
When is the next official towny release? The last one was 6 months ago, on September 2nd.

Is towny war flags still not supported?

Is there a way to have towny war always active? It turns off if the server restarts. I'm wondering if there's a way to have things like overclaim and other options on 24/7. 

Is towny still being fully supported? I've noticed releases and updates have significantly slown down. They used to be literally daily which was insane, to now it looks like a monthly basis.

**Comment by LlmDl** [comment]
Next release will be out when it's ready.

Flag war is not supported, anyone is welcome to work on it and submit tested/working PRs to the Towny project.

The war event doesn't currently support being on all of the time or overclaiming.

Things are slow right now because I have a lot of (good) things going on in my life that are keeping me very busy. 

I'm looking forward to having more time to work on things but also having other people step up to the plate to handle some of the bugs we need to close in order to get the next release out. The next release will be the last updates for pre-1.13 versions of Minecraft so it is important that we close as many bugs as possible before that.
