### ISSUE TITLE
Breaking Blocks when in jail let users clip blocks.

### ISSUE THREAD

**Issue by Blackyvk** [TownyAdvanced/Towny#3206]
### What steps will reproduce the problem?
1. create a jail
2. send resident to jail
3. jailed resident destroy any blocks and walk on that direction
4. jailed resident gets this error and clip through the blocks like a ghost, can be front or down, any way you  can go.

![imagen](https://user-images.githubusercontent.com/9063912/54888705-d0a31680-4e75-11e9-8fc7-af7987a7d8d5.png)

### What is the expected output?
1. Not doing the above... player shouldnt clip walls.

### What is your Towny version?
0.93.0.4

### What is your spigot/craftbukkit version?
1.12.2 or 1.13.2 tested on both. spigot and paper.

### Please use Pastebin.com to link the following files:

1. Your full server startup from the logs\latest.log : https://pastebin.com/raw/kM9JsuuX
2. Your Towny config.yml  default file
3. Your townyperms.yml : default file
4. Your log's error :   no console errors

**Comment by LlmDl** [comment]
This happens when a player walks into a door and breaks it. It is client side, as the door doesn't actually break. Not much we can do about this besides canceling their movement.

**Comment by Articdive** [comment]
There is really not much we can do here tbh, the worst part is we could do something but it would be keeping track of every single movement and if it's possible in every orientation of for example a door.
You're better off using an AntiCheat plugin to take care of this, since they can use that information much better than just us for that 1 thing (block clipping). They could stop speed hacks, fly hacks, potion hacks for example.

**Comment by Blackyvk** [comment]
Weird is that this only happens on a jail plot, in normal plots  the door doesnt let you go through.

**Comment by LlmDl** [comment]
I took a look at the code out of curiosity but couldn't find anything related to jail plots when it comes to breaking blocks. Sorry we cannot do something more about this, but anti-cheat plugins are probably the solution to this as it is their specialty.
