### ISSUE TITLE
1.14 towny server lags 

### ISSUE THREAD

**Issue by Feldmarschall** [TownyAdvanced/Towny#3237]
Problem:
High performance lags, because townys "MobRemovalTimerTask".

Towny v0.93.0.0 Total: 10.9 s	Pct: 41.79%
   Pct Total	Pct Tick	   Total	      Avg	 PerTick	     Count		Event
      41.76%	4,356.52%	 10.89 s	 2,178.26 ms	 0.0	       0.0k	    Task: MobRemovalTimerTask(interval 100)

[https://imgur.com/a/xgXIEmW](url)

### What is your Towny version?

0.93.0.0

### What is your spigot/craftbukkit version?

git-Spigot-1eece4f-a584320 - 1.14-R0.1-Snapshot

I hope for a fast fix. Towny would be such a good plugin, but the development stagnates...
Best regards.

**Comment by BarnabyD** [comment]
Yeah this is an issue. To get my server running smoothly for 1.14, I commented out MobRemovalTimerTask and whacked a message on login warning players about the mobs. :')

So now I've had some time, I've dug deeper and found what is causing the lag.
[`livingEntityLoc.getChunk().isLoaded()`](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java#L74)

Currently testing out looping though loaded chunks, then looping though the entities, rather than checking the chunk for each entity. Seems to be working so much better, but I don't have a huge player base, so unsure if it will worse the more players on. 

My next question is, do we even need to do that check? As [`world.getLivingEntities()`](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/tasks/MobRemovalTimerTask.java#L72) should only return loaded mobs, should it not?

**Comment by LlmDl** [comment]
@BarnabyD looks like something to investigate. If you find something that works better submit a PR.

@Feldmarschall ticket form was skipped, this ticket needs to be re-made with the form completed.
