### ISSUE TITLE
Discussion: Changing Towny's License

### ISSUE THREAD

**Issue by Articdive** [TownyAdvanced/Towny#3255]
Something I realized is, that to be compliant to bukkit, we might need to switch to a GPL-Variant of a license.

**Comment by TheFlagCourier** [comment]
It was under the Eclipse Public License at one point in time, at least according to the Google Code archive. This would have been around the 0.78 series...

But yeah, if a license issue ever arises, it's probably better to stick to one compatible with the Bukkit API, be that under the General Public License or perhaps it's 'Lesser' form. It's also probably for the better, since Creative Commons licenses are not meant to cover software.

**Comment by Articdive** [comment]
Although question is, if we need permission from @ElgarL to do so.

**Comment by ElgarL** [comment]
As Bukkit itself doesn't have a valid license I'd not be too worried about using a compliant license.
The Bukkit legality/License issue is the main reason I stopped working on Towny. When the platform is breaking licensing laws I can't support it.
However, if the license needs to be changed for Towny it would be up to Llmdl.

**Comment by Articdive** [comment]
> It was under the Eclipse Public License at one point in time, at least according to the Google Code archive. This would have been around the 0.78 series...
> 
> But yeah, if a license issue ever arises, it's probably better to stick to one compatible with the Bukkit API, be that under the General Public License or perhaps it's 'Lesser' form. It's also probably for the better, since Creative Commons licenses are not meant to cover software.

I would take the normal GPL, as the 'Lesser' form would allow paid distributions of Towny, we would need to check if we can keep the system of, add your changes into Towny instead of creating your own version is possible.

**Comment by TheFlagCourier** [comment]
The normal GPL already allows people to set up paid distributions, so long as the source code is provided. But yeah, GPL would require changes to be committed back, while LGPL is more lax there. Unless the focus is on letting others hook into Towny without arbitrarily forcing them to use a (L)GPL license themselves, GPL is the way to go.

At the same time, we would need to check the licenses of the dependencies used. I think the only one that would need to be compiled into the jar would be CitizensAPI based on [it's documentation](https://github.com/CitizensDev/CitizensAPI#maven). (Which is unfortunately incompatible with the GPL [according to the FSF](https://www.gnu.org/licenses/license-list.en.html#OSL). ) Not sure if that would make the final product invalid under the standard GPL, or not... #not-a-lawyer

**Comment by creatorfromhell** [comment]
I would suggest AGPL as it covers a clause that allows private modifications without the need to release the source code in GPL licenses.

**Comment by TheFlagCourier** [comment]
It'd keep any valid forks open source, since network connections to any server running it would constitute distribution. Any forks from that point on would have to share their modifications by linking to their source code. Other than that, it's virtually the same as the GPL, GPL just doesn't inherently recognize Network Access as distribution.

I'd say it would meet goals to keep the project open, and any forks, but it'd also have the side effect of pissing off some server owners as we'd essentially be saying: "Hey, this server uses Towny (or TownyFork). Want to compete with this server for it's player base? The source is available for use here."

For that reason, AGPL should not be the next license, unless we can get a majority of server owners to agree to it prior to adoption. I do still think a GPL compatible license is the right way to go, but since we only shade dependencies in, we could go with any valid OSI approved license that meets the values Llmdl wants to keep with the project.

**Comment by LlmDl** [comment]
The main things I want out of a license (if we do end up changing it. I don't see it as a high priority at all due to the licensing situation of bukkit itself.) that keeps these things at the forefront:

1. No distribution to the general public of forks.
    - This is to keep what happened to Factions from happening to Towny. We don't want things to collapse into many versions of Towny, which becomes a nightmare to support.

2. No money. Selling parts of the plugin for real dollars is something I do not appreciate in the slightest. I don't even like making money for the time I put into Towny. It should be a free experience for the players playing Towny and Minecraft.

Lesser things to consider: 

- Forks should probably send their helpful code back to us.
- Private server forks should probably not be harassed (unless they're making money using Towny.)


So if there's a magical license out there that does this and not a lot more then I'll hear it.

**Comment by TheFlagCourier** [comment]
Right now, I do think this still deserves discussion. The Creative Commons licenses are great for audio, visual, or written works, but are not suitable for any software project. 

- Forks: No-Derivatives currently allows for private forks but does not allow for public forks of any kind, even if they don't provide a binary package. There's just not any distinction made between source-code and binary within Creative Commons licenses' terms. This clause further makes it imperative that modifications are made directly onto the main repo rather than pull-requested in.
This is counter-intuitive to both the lesser things you think should be considered with forks, and the idea of using a publicly accessible scm like git in the first place. I know we're fine with public forks as long as they aren't intended for redistribution and have the intent to PR back, but the license just does not allow for that. (In a sense, we're all violators of this license.)

- Copyright: Currently, any one of us contributors can request that their code be removed from the project, or have the repository taken down. I think copyrights must be addressed - either assigned to the project or expressly waived by the contributors in relation to the project and it's API.

- Use as an API / Interface: Right now, the TownyAPI class(es) are not provided under a separate license / repository. I think using Towny as an API, or interfacing with it, needs to be protected. Otherwise, projects like TownyFlight, and even TownyChat, may actually be license violations.

**Comment by ElgarL** [comment]
Seeing as I decided on the license, wrote the API and wrote TownyChat I'd argue there is no violation.

**Comment by TheFlagCourier** [comment]
Yeah, using TownyChat and TownyFlight are probably not the best of examples for that... Perhaps TownyGUI or a similar plugin not officially part of the TownyAdvanced group would have been a better one.

**Comment by ElgarL** [comment]
Yep a better example. However, until the Oracle law suit is finally decided (at appeal) theres no real need to make any decisions on API copyright use.
