### ISSUE TITLE
Suggestion: Ally Town Perms

### ISSUE THREAD

**Issue by ZebZ** [TownyAdvanced/Towny#3294]
Hello, i have been using the permission node towny.claimed.townowned.Switch/itemuse for a custom made town Guard rank. Though we want to add a national Guard rank but lack the functionality for it.

Would it be possible to create a permission node like "towny.claimed.nationowned.build/destroy/switch/item_use"??

**Comment by LlmDl** [comment]
It is possible but we have refrained from doing so in the past because for every node we add the performance hit becomes that much larger when recalculating a player's permissioncache. Right now we have 3 of the claimed nodes, and then the standard permission check, adding another claimed node would increase all permission checks by another 25%.

**Comment by LlmDl** [comment]
I should have said that I believe you could achieve what you want via a separate plugin that uses the Towny API.
