### ISSUE TITLE
Crossbow damage in towny claims

### ISSUE THREAD

**Issue by Kbryst** [TownyAdvanced/Towny#3332]
### What steps will reproduce the problem?
1. Create a firework rocket with any firework star (make sure it has the firework star).
2. Put it on ur offhand to load a crossbow.
3. Shoot a player ina town claim area (pvp is turned off)

### What is the expected output?
1. Players are taking damage from it and are able to kill in town claimed areas. Expected output: No damage taken.

### What is your Towny version?
0.94.0.0
*Did not test on latest dev build

### What is your spigot/craftbukkit version?
Paper 1.14.4 - 146
(This was first reported to me on 1.14.2)

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
Unable to obtain these at this time. Did test this on a test server with the latest versions of essentials and vault. 
2. Your Towny config.yml :
Default config
3. Your townyperms.yml :
Default townyperms.yml
4. Your log's error : 
No error generated

Extra note: World guard does not protect from this either. Will report to world guard.

**Comment by LlmDl** [comment]
This ought to do the trick until the Bukkit API get the ability to see who's shot the firework:

https://github.com/TownyAdvanced/Towny/releases/tag/v0.94.0.3

**Comment by silverwolfg11** [comment]
This fix doesn't work and throws an NPE in console for me (using Towny Version 0.94.5). 
I believe the error is caused because townyWorld is null when it's passed through the locationCanExplode method in the TownyEntityListenerClass.
Simple fix is to define townyWorld either within the if-statement that checks for a firework or at the base initialization (because all of the initializations of the variable are the same).
