### ISSUE TITLE
Fix a couple things when Cyrillic characters are used.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#3385]
- [x] Archive backups don't like data\towns\townname + nationname files when they're in cyrillic.

- [ ] Mentions in the logs like debug startup messages show ???? in log file/console.

- [ ] Town and nation lists show ???? characters in console only,

**Comment by Articdive** [comment]
Arching backups works completely fine for me: https://gyazo.com/c1acbc021ef7880bdb13bcdfc4cf7e0f
Mentions in the logs and console: I'm going to send a PR into Spigot to switch them over to UTF-8 since Windows by default has the file encoding cp1252 adding the java flag -Dfile.encoding=UTF-8 should actually fix up the names in the log file, not sure about the console though. It might not ever be possible to make the console output the correct names since Windows is annoying.

Anyway what works by all means is
plugins/towny/logs/debug.log, towny.log and money.log they contain the UTF-8 characters correctly.

**Comment by LlmDl** [comment]
Sounds good, maybe my winrar is just really old or maybe I left out the language files when I installed it. Either way I'm pretty sure russians with windows can probably see cyrillic characters in their logs.
