### ISSUE TITLE
Remove deprecated Vault calls in TownyEconomyHandler

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#3425]
Means finding or making a common offlineplayer call for other economy plugins to use.

**Comment by LlmDl** [comment]
Calling this one off, there's pretty much no way that we do this without completely borking support for one or more eco plugin's existing town/nation banks.

**Comment by lokka30** [comment]
> Calling this one off, there's pretty much no way that we do this without completely borking support for one or more eco plugin's existing town/nation banks.

Hi @LlmDl, is this still the case?

**Comment by LlmDl** [comment]
It is somewhat still the case. Potentially we could ask the balances on load, then convert to all new accounts based on town and nation uuids, then zero-out the old accounts (because vault doesn't have delete methods.) We would need a way of knowing the conversion was done. 

The debt accounts for the towns would also need something, as we couldn't be using the town UUID for that as well.

**Comment by lokka30** [comment]
> It is somewhat still the case. Potentially we could ask the balances on load, then convert to all new accounts based on town and nation uuids, then zero-out the old accounts (because vault doesn't have delete methods.) We would need a way of knowing the conversion was done.
> 
> The debt accounts for the towns would also need something, as we couldn't be using the town UUID for that as well.

Would it be possible to store town, nation, debt, etc. account balances in Towny's own database instead of through Vault?

Currently the Vault situation here has issues:
- The methods used are only meant to be supplied with player usernames - Towny is supplying town/nation/debt accounts as well.
- The methods used have been deprecated for a while, so there's a chance that the Vault author will remove them. I doubt they will since it will break old plugins, but still a possibility.

**Comment by LlmDl** [comment]
The Vault author has no plans to remove the String account type. Towny cannot do the things that each economy plugin does with regards to currency customization, so storing it internally is also undesirable.

At some point we'll gather all of the balances up and make our own UUID with them, then zero out all of the previous town/nation/debt accounts.
