### ISSUE TITLE
Suggestion: Choose your Nation's type of Government

### ISSUE THREAD

**Issue by Wynn33** [TownyAdvanced/Towny#3469]
Hi, i would like to see a feature that is based in some of the strategy games that i've played (eu4 mainly).

The feature is that when you create a nation you could choose your government type between this three types:
-Republic (Democratic one, authoritarian, communist, oligarchic, fascist, pirate republic, etc)
-Monarchy (Absolutism, Parlamentary or Constitutional, imperial, Aristocracy, commonwealth, etc)
-Teocracy: Holy Order, Papacy(? or metropoli (under control of a Patriarch or a Matriarch) Holy State.

And also it should be added the decision to switch between them with another feature like administrative power or popular choice.

Apart from that the possibility to choice your title, for example. i want to be crowned as Imperator but other player as Sultan or King or Dux or whatever and you can choice your own title.

That's all, thank you for your attention.

**Comment by LlmDl** [comment]
Tickets like these are nice but they usually don't go to far. I try to not add in things that are usually Roleplaying and which are not tied to something tangible in-game. Nation kings can already assign themselves any title they want, which will override the prefix Towny pulls from the nation_levels in the config.

In order to accomplish this sort of ticket, you'd need to have tangible things/rules/limits for all of the above types of government and the behind-the-scenes support for all of those rules/limits/features in the code for Towny.
