### ISSUE TITLE
Suggestion: Option to have towns flip to conquering nation in war.

### ISSUE THREAD

**Issue by pegla2108001** [TownyAdvanced/Towny#3477]
**Please explain your feature request to the best of your abilities:**
Basically when a town is conquered (either by killing its members or standing on the homeblock) it goes to the attacking nation. Togglable war type: taking towns/taking town chunks as seen in my last suggestion.

**Comment by LlmDl** [comment]
So I've been thinking about this one and how it would work into or alongside of the last one I did (conquered townblocks go to the attacker's town permanently.)

Right now a town that has been conquered using the old system, after the war they have no homeblock until they set a new one. Usually this would mean the the town has had at least one complete line of townblocks taken all the way to their townblocks, probably more than just one linear line. Losing a homeblock would probably be fairly crippling to the town.

Would this ticket's request be something that is used alongside the last ticket? The conquering town is basically occupying the losing town, and pulling it into the nation, or does the nation consume the entire losing town while it retains all of its original townblocks?

Do we do both?

**Comment by Goosius1** [comment]
Hi @LlmDl !. 

Given I love towny, I have been working on a new optional Towny war system for a few months which might help with this ticket.

It is called 'Siege War'

In brief, it works by Nations besieging and conquering/flipping towns in their entirity, rather than piece-by-piece.  This has the key benefits of allowing:
1. War on demand       
2. Nation Growth via conquering of towns. (!)
3. Complete protection of town property. (!)  
   (_Because war spoils are limited to a one-time plundering of credits, plus ongoing taxation,
      so no beautiful structures or landmarks need to be destroyed_),

I hope to have a PR over to you in the next few weeks.

Regards,  
  Goosius

**Comment by LlmDl** [comment]
Sounds interesting @Goosius1, I'll look forward to seeing the PR.

**Comment by LlmDl** [comment]
This one is done as of https://github.com/TownyAdvanced/Towny/commit/537d8aa05c709c2d36d3660166459eb2a10113c8

Part of the forthcoming 0.95.2.1
