### ISSUE TITLE
Suggestion: Set the maximum distance a claim in a town can be from the home block

### ISSUE THREAD

**Issue by drewdorris** [TownyAdvanced/Towny#3498]
Similar setting to nation distance limit, but with claims. This would prevent towns from claiming a long distance out of their way to block another town. Making it configurable with the default town levels would be nice, but it could just be a singular setting.

This would need a check when moving the town block to make sure existing claims aren't too far

**Comment by alynchbetbright** [comment]
Some thoughts on this which might help:

1. This looks like a great way to restrict each town to a very specific area,
    (a restriction which I believe is not currently possibly 
      .... because theoretically you can 'walk' your town border out to any location)

2. The way it works with the 'outposts' feature seems important to consider:
    i.  If the option to have outposts is allowed
        and outpost are allowed within the new boundary
        then outposts becomes much less useful, and the configured cost might need reduction.         
        ....because rather than paying a large extra cost  for an outpost 10 blocks away from the town
        ....it may work out cheaper or easier to simply 'walk' the border out there

  ii. If the option to have outposts is allowed
      then presumably outposts would not be allowed outside the new boundary,
      because this would seem to circumvent the whole point of the idea.

  iii. If the option to have outposts is NOT allowed with this new limit, 
       then the two configs need to be co-ordinated carefully e.g.
       ....perhaps throw an error on server start up if the server admin tries to enable both.....

**Comment by Goosius1** [comment]
Some thoughts on this which might help:

  1. This looks like a great way to restrict each town to a very specific area,

  2. The way it works with the 'outposts' feature seems important to consider:

    i.  If the option to have outposts is allowed
        and outposts are allowed within the new boundary
        then outposts becomes much less useful, and the configured cost might need reduction.         
        ....because rather than paying a large extra cost  for an outpost 10 blocks away from the town
        ....it may work out cheaper or easier to simply 'walk' the border out there

    ii.  If the option to have outposts is allowed
        then presumably outposts would not be allowed outside the new boundary,
        because this would seem to circumvent the whole point of the idea.
  
    iii.  If the option to have outposts is NOT allowed with this new limit, 
         then the two configs need to be co-ordinated carefully e.g.
        ....perhaps throw an error on server start up if the server admin tries to enable both.....

**Comment by LlmDl** [comment]
Having this idea mesh with outposts is very  difficult.

To get whether a new claim is within the distance is fairly easy. To test whether a town should be able to move its homeblock is entirely different. Since we don't track towns and their outposts congruity we cannot tell that that far off outpost isn't a part of the town's main landmass.

So in this system are we limiting outposts to the same distance of the homeblock as normal plots? Are we only allowing outposts to be made in other worlds from the homeblock?

**Comment by drewdorris** [comment]
I did not consider outposts as we have them disabled on our server, haha. I would think that outposts shouldn't be tested for distance, since they're meant to be detached and in a different location. I would just like the ability to keep the main town areas in a more compacted area, and outposts can be left alone.

**Comment by LlmDl** [comment]
That's sort of what I figured. There's still a problem of the normal plots surrounding the outpost. We cannot tell that they're not part of of the main town land mass.

**Comment by OskyEdz** [comment]
Two things to point out.
Pose that you're on a server that already has mega huge towns.If you allow 10k in town size, you must allow a higher maximum distance, making the option quite punk.

The problem with outposts could potentially be more challenging if the outpost were ever to connect with the city itself (like a town teleport because of the big town size).

It would be better to make plot-claiming to always check for nearby towns, if you have problems try to raise that value.

**Comment by LlmDl** [comment]
I think I'll leave this up to a plugin using our API. There's too many conflicting settings in Towny for this to mesh well. Someone that wants to have this specific feature can probably pay to have it made.
