### ISSUE TITLE
Suggestion: Prevent "town falls after bank emptied by assistant" grief

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#3553]
**DESCRIPTION**
- This grief is when a town assistant player completely empties a town bank just before the update tick. The town then fails to pay upkeep and goes into ruin.
- I have seen this multiple times on servers, and it causes a lot of aggro and headaches.
- Just recently this happened to a very nice town Woke on Minesuperior, which reminded me of the issue,

**PATCH**
- I suggest we put something in to prevent this grief, and I would like to hear what people think is a good option:
- Here are some options:

----------------------------
**OPTION A**
- Have a server-admin-configured "minimum town balance", below which only the mayor can withdraw or spend.
- This would be something like  "500 gold _per_ claimed townblock".... enough for taxes & upkeep & potential war plunder/robberies  for like 1 week.

_Pros_   
1. Mayors don't have any new operations to worry about.

Cons:  
1. Server admin has a little more ongoing work to do, to keep the value at an appropriate level.

----------------------------
**OPTION B**
- Have a mayor-configured "minimum town balance". This could be a simple flat amount e.g.  20,000.

_Pros_   
1. Because mayors can control the amount, they can manage their absences in a more fine grained way e.g. if they are going on holidays for 2 weeks, they can set the minimum balance to be very high.
2. Server admin doesn't have to do anything...theoretically.

_Cons_
1. Server admin does, practically, have to educate mayors on the system, and still deal with complaints from griefed towns which did not use it right.
2. This would be another operation which mayors would have to learn how to do to manage their towns well.

----------------------------
**OPTION C**
- If the town runs out of money, put it into a 'bankrupt' state for 1 week (duration configurable by server).
- During this time, the town still works fine, but if enough money is not deposited to repay the debts, it gets ruined

_Pros_   
1. Mayors don't have any new operations to worry about.
2. Server owners don't have much to do, except reconfigure the bankruptsy duration if they wish.
3. The 'recovery window' can be controlled much more reliably.  E.g. nobody has to try and guess how much money a town might lose in 5 days.   We simply know that a mayor can go on holiday for 5 days and their town will still be standing when they come back.

_Cons_   
1. Probably more coding work compared to the other options.

----------------------------

**Comment by LlmDl** [comment]
This is really a mayor problem caused by making the wrong person an assistant, or a server admin problem giving assistants the ability to withdraw money. That said I think the most realistic option is A or B. Once a bank is low enough then there's no way to withdraw or spend money. 

This seems easy enough but you run into trouble when things aside from claiming are looked for how a town/nation bank can lose money.
- DeathPayments from the town/nation banks, do we just stop paying out? 
- Nation tax, does the town just stop paying taxes when they hit their limit and get booted from the Nation like they're already broke?
- There are probably more things that would have to be factored in.

If we choose Option A, an amount set by the server owner, this doesn't seem like a server that should be using upkeep to begin with. They want to nuke towns, but they don't want to have towns fall fast? Make the upkeep low or close to 0.

**Comment by Goosius1** [comment]
Yea that is true, this situation does stem from the Mayor trusting the wrong player.
An even if the bank-withdrawal grief is technically discouraged, no doubt say such a town assistant would find a different way to cause trouble.

However, perhaps the limitation (using A or B) might provide a small improvement without too much coding effort.

In terms of what operations the potential limitation could affect, perhaps a good benefit could be achieved by limiting just a small few operations and leaving the rest as-is ?   e.g.

**Not Allowed**
- Withdraw from bank (except by Mayor)
- Claim
- Claim outpost
- (+ generally all payments which benefit the town)

**Unaffected**
- Town upkeep
- Death payments  (because otherwise combat decisions may get altered in a complex way)
- Nation tax  (because otherwise a town could withhold tax from an occupying nation)
- (+ generally all payments which benefit another party instead of the town)

**Comment by LlmDl** [comment]
What's stopping the roque assistant going and getting himself killed over and over again to take the money anyways?

Why doesn't the server admin/moderator just ban the assistant from the server?

**Comment by Goosius1** [comment]
Interesting.

For dealing with a dedicated griefer with a technical solution, perhaps all obvious money-drain holes then would need to be plugged together for it to be effective (including that multi-death one).

Yea I think ideally the server mods would spot the problem asap and both ban player + restore the town.

**Comment by LlmDl** [comment]
I've labeled this one seeking community feedback, maybe we'll learn if this is something admins want that way. Overall I'm leaning towards calling this one of those problems that while Towny could handle, it really isn't a Towny problem but rather an issue with the entire chain with the blame landing at the player level: Plugin<Admin<Mayor<Player.

**Comment by OskyEdz** [comment]
I can see option C working. By rather then bankrupt (else by choice bankrupt or ruins)  you should  be able too reboot a town. 
Keep the town in file just mark it as bankrupt/ruins and when the mayor gets back and see the damage (or any other reason the town went down.) He or she can start it upp if enough  money is provided for all the claims or otherwise reasonable amount set by config. The mayor would lose players,  but by then everyone will know if they wanna come back to the town or not.  (A town with low bank might not be so attractive for everyone, going bankrupt can say one or two things about the mayor if it is not by grief.)

**Comment by Goosius1** [comment]
Related Ticket:
[https://github.com/TownyAdvanced/Towny/issues/3657](url)

**Comment by Momshroom** [comment]
I think the ruins idea would actually serve to fix this pretty well.  Yes, assistants could still do this, but it couldn’t be over claimed and could be fixed.  It seems a good middle ground without causing more loopholes than it prevents.

**Comment by bartyrealms** [comment]
The only risk appears to be assistants just being able to steal from the town. No permanent damage is actually done.

**Comment by Goosius1** [comment]
- This ticket is resolved now (fixed in SiegeWar branch)
- By implementing a 3 day (default) ruin time, along with a town reclaim mechanic (available after 1 day by default), my initial concerns on raising the ticket are now sufficiently addressed.
- The indicated solution seems to be working fine on trial servers
- As per community feedback, it appears sufficiently simple not to cause other unintended effects.

**Comment by Goosius1** [comment]
This ticket should be even better resolved by the town-bankruptsy mechanic  
(which much more simply prevents a town falling if it runs out of money)
