### ISSUE TITLE
Suggestion: Regions and Counties

### ISSUE THREAD

**Issue by EOT3000** [TownyAdvanced/Towny#3559]
A Nation leader can create regions, and set their names (state,  province, etc.). They can also choose the leader of region, called a lord or something, and nation leaders can divide towns between regions.
The lord of a state can create counties, and divide their towns between the counties. They can also choose what all counties will be called, and the county leader, called a clerk.

A resident of a town can own plots their region's towns' . 

Also, their will be special kinds of plots, owned by the nation, region, or county.

These plot types can be roads or jails, with nation plots increasing the nation's upkeep most, and county plots increasing the county upkeep very little. Jails are more expensive. The owner of a server can set a max plots per person, meaning if a nation has 10 people, and the max plots per person is 10, the nation can claim 90 (doesn't count the king) nation plots.

I wanted to see feedback for this idea before making a PR

**Comment by LlmDl** [comment]
This is something that would require two new layers added to Towny, the Towny database, the command structure, the permissions system along with the ranks, and probably other places as well.

Rather than just Nation > Town, you're talking about Nation>Region>County>Town. On top of that you're proposing that Nations own land. Currently only Towns own land in the database.

These are massive changes that in the end mostly boil down to adding roles for role-playing.

Jails can already be made more expensive to make, as of 0.95.1.0 or 0.95.2.0.

I do not see this happening, sorry.

**Comment by EOT3000** [comment]
You can set a plot type, like Jail, Shop, Farm. Nation plots should be normal plots of the nation's capital, not affecting its upkeep, of a new type: Nation.
Same with Regional plots being owned by a region's capital, of a new type : region
Same with county
