### ISSUE TITLE
Suggestion: Monarchy system

### ISSUE THREAD

**Issue by Ninjagoat73** [TownyAdvanced/Towny#3585]
First of all a big money loss for the town would  happen for the town (could be said for coronation, funeral so on) as you said a the heir would be a back up, BUT only people with a specific rank in the town/nation could become king (so like if the mayor gave them a role called lord or something they could be made heir), but this would create an infinite loop of kings never dying, so those who have been king cannot be king again (could be forever, could be until a new war starts), still the new king could make new lords, so there would be a restriction needed where you cannot make lords while at war. 

(i was told to copy and paste my last msg, if needed i can figure out something more detailed)

**Comment by Goosius1** [comment]
Hi,

Could monarchy effects be made available outside of war events also?

I think this would be good for peaceful servers, ones which used other war systems too, or just for improving the peacetime experience.

So for example ---- if a king dies by assasination (or any means?), but does not have any succession lined up:
- a period of anarchy occurs ?
- the nation cannot collect taxes for 1-3 days ?
- pvp is enabled in all towns for 1-3 days ?

-----

Apart from cool effects I am wondering about the practicalities of a different player becoming a nation king e.g.

* if the change is temporary then the original king will still surely call the shots, thus the 'heir' would really function more like a visier or regent, just technically carrying out the kings instructions. Perhaps then the title of this player should be regent, high councellor or visier ?

* if the change is supposed to be permanent Im not sure that would work. Either the heir would be unhappy due to simply technically carrying out the old king's commands all the time, or the old king would be unhappy that the heir is actually taking their position in the server community even though they did not want to retire from that position.

* For a true 'heir', perhaps use that term only for a player who truly will take over from the King when they leave the server ?. So if the king is offline for a month, then the heir ascends to the throne then ?

**Comment by LlmDl** [comment]
Most of this stuff ends up falling into the realm of role-playing and what doesn't could probably be accomplished with a secondary plugin that uses the TownyAPI.
