### ISSUE TITLE
Suggestion: Cross-server support

### ISSUE THREAD

**Issue by jordanwilliams1** [TownyAdvanced/Towny#3637]
**Please explain your feature request to the best of your abilities:**

I've spoken to a few servers owner the past few months and some of them are starting to abandon towny and creating there own "towny" plugin that will work across multiple servers. This is due to 1.14.4 - 1.15 terrible performance and requiring us server owners to run multiple servers per world. 

Could you please think about making towny cross-server compatible?  

Example: if your in server 1 and you do /t spawn and your town is located in server 2 it will tp you to server 2 in your town?.

You would have to state in each towny config what bungee this instants of towny is running on.

**Comment by LlmDl** [comment]
I don't think this will happen, sorry.

**Comment by Pet0203** [comment]
How would you even go about sharing a world between two different servers?

**Comment by jordanwilliams1** [comment]
@Pet0203 Sorry, I Mean. 1 server per world with everything linked to each other. Nearly every plugin I run supports multi-server support apart from towny. An example here would be: play.craftadia.com

They run a server for every world they have. A lot of other 'towny' servers are in the process of making their own towny plugin "apparently" to support this.

**Comment by LlmDl** [comment]
You're jordan who runs DifferentCraft, you violate the Towny license by selling Towny townblocks. I've asked you to stop selling those townblocks. Considering your server has already made more than $1500.00 this month in 'donations' I think you can probably do just fine without selling Towny townblocks.

Selling Towny on spigot would also be in violation of the Towny license, so that will not be happening.

I do not code Towny to make money, I do it as a hobby. The more I have to deal with servers that are in violation of the Towny license for selling townblocks, the more likely it will be I remove the ability to sell townblocks altogether.
