### ISSUE TITLE
Idea for discussion - Combine War Systems

### ISSUE THREAD

**Issue by Goosius1** [TownyAdvanced/Towny#3649]
### Description
Today there are two war systems available with Towny, with more on the way.

It strikes me that if these war systems were to be combined at some point into a single 'towny war' system, then there would be less code overall, making all war features possibly easier to support, and also allowing more flexibility for server admins to choose from all the features people have made, to configure exactly the system they want e.g:

Server config options:
- destructive or non-destructive to builds
- time sensitive event or war-on-demand
- chest plunder or town credits plunder
- full town occupation or just plots occupation.
- flag represented by fence with wool, or banner.
- Nation vs. nation, nation vs. town , or town vs. town.

So thats the pluses. On the minus side:
- This would likely be a (very..) big initial coding effort
- Because of shared code, some future changes to such a system could require a bigger re-testing effort than with the present separate-systems model.

This is quite a strategic thing to consider, thus from me this is an idea, not a highly analysed suggestion as such, but if it does happen to make sense to the Towny team, I can assist etc.

**Comment by bartyrealms** [comment]
This would be good to reduce confusion and complication between all war systems. However, I think they should continue to be separate, as they are all very complicated systems on their own.

**Comment by LlmDl** [comment]
I imagine some of the common-ground code between the three modes will get combined at some point, like how the EventWar got upgraded to use the FlagWar's blockpermissions config section.

But combining all of them into one system will probably not happen in full, partly because there's different people supporting each one.

**Comment by TheFlagCourier** [comment]
Yeah, the common ground could be generalized, with each war-type just expanding on them as needed. That might also give external 3rd-party (ie WarsForTowny), or experimental (SiegeWar), systems better / extended access to preexisting methods.

**Comment by TheFlagCourier** [comment]
@Goosius1 @LlmDl Started the process in the [refactor/WarSegmentation](/TownyAdvanced/Towny/tree/refactor/WarSegmentation) branch. Not ready to PR yet, as I have no experience with EventWar to add that to it, and other additions may be worth considering as well.

**Comment by alynchbetbright** [comment]
Ideas for things which could be generalized:

**1. Tick Control**.......... Many systems have a need for timer 'ticks', Most systems seem to require a short tick (e.g. 5-30 seconds) to make some update to a battle while players are occupying a flag zone.  Some systems also have a moderate tick also (e.g. 1 hour).  Example: In siegewar, this moderate tick is used to check occasionally for town ruins removal.

**2. Town perm changes**.........Many systems forcibly change town perms when a town is attacked. Examples: In siegewar, PVP is enabled, in other systems, block destruction is enabled.
(Note that I have found it more robust/stable to simply intercept and amend (if required) the returning value from getPermX() type methods ...... rather than actually changing the perm in the object/db then changing it back when the battle is over)

**3. Flag Behaviour** ..... Many systems use in-game representations of war flags (siegewar uses normal minecraft banners, some systems use wool on a fence post).  These object sometimes need to be temporarily indestructible, or otherwise have special protections.  Also often enhanced visibility is desirable (e.g. via fireworks, smoke etc).

**4. Town Capture** .... Multiple systems seek to provide the option for town 'capture' by a hostile nation.  

At face value, the town is simply added to the nation.  

But there are many complicating factors. Obviously such a town could simply leave the nation immediately after, thus they must be prevented (siegewar uses a java long 'allowedLeaveTime', which is scanned when a leave is attempted. An error is given is the time has not yet been reached. This has proven robust and allows precise timing of the leave date).

Also the mayor could simply delete the town or remove money from their bank (allowing it to fall to upkeep) - both ways are effective in escaping the nation. Siegewar solves this common issue by using a 'ruins' system, so that Escape-From-Nation is both immediately possible (so no absolute confinement of the town in nation), but also impossible to meaningfully exploit to avoid occupation or taxes.

**5. Town Revolt** .... Similar to the previous common issue, any system with town capture may also wish for towns to be able to leave at some point. Some sort of timer mechanic is usually used etc. (The siegewar mechanic was described above).

**6. Neutrality** .... Many systems have the need for towns (and even nations) to be immune to war or war-effects. Siegewar has a well developed town-neutrality mechanic, other systems may have more well developed nation-neutrality mechanics.

**Comment by Goosius1** [comment]
Ideas for things which could be generalized:

1. Tick Control.......... Many systems have a need for timer 'ticks', Most systems seem to require a short tick (e.g. 5-30 seconds) to make some update to a battle while players are occupying a flag zone. Some systems also have a moderate tick also (e.g. 1 hour). Example: In siegewar, this moderate tick is used to check occasionally for town ruins removal.

2. Town perm changes.........Many systems forcibly change town perms when a town is attacked. Examples: In siegewar, PVP is enabled, in other systems, block destruction is enabled.
(Note that I have found it more robust/stable to simply intercept and amend (if required) the returning value from getPermX() type methods ...... rather than actually changing the perm in the object/db then changing it back when the battle is over)

3. Flag Behaviour ..... Many systems use in-game representations of war flags (siegewar uses normal minecraft banners, some systems use wool on a fence post). These object sometimes need to be temporarily indestructible, or otherwise have special protections. Also often enhanced visibility is desirable (e.g. via fireworks, smoke etc).

4. Town Capture .... Multiple systems seek to provide the option for town 'capture' by a hostile nation.

At face value, the town is simply added to the nation.

But there are many complicating factors. Obviously such a town could simply leave the nation immediately after, thus they must be prevented (siegewar uses a java long 'allowedLeaveTime', which is scanned when a leave is attempted. An error is given is the time has not yet been reached. This has proven robust and allows precise timing of the leave date).

Also the mayor could simply delete the town or remove money from their bank (allowing it to fall to upkeep) - both ways are effective in escaping the nation. Siegewar solves this common issue by using a 'ruins' system, so that Escape-From-Nation is both immediately possible (so no absolute confinement of the town in nation), but also impossible to meaningfully exploit to avoid occupation or taxes.

5. Town Revolt .... Similar to the previous common issue, any system with town capture may also wish for towns to be able to leave at some point. Some sort of timer mechanic is usually used etc. (The siegewar mechanic was described above).

6. Neutrality .... Many systems have the need for towns (and even nations) to be immune to war or war-effects. Siegewar has a well developed town-neutrality mechanic, other systems may have more well developed nation-neutrality mechanics.

**Comment by LlmDl** [comment]
So one of the projects I think I will be taking on over the next months will be the consolidating the Towny build/destroy/switch/itemuse/pvp/explosion/fire/mobs decisions into an event (or events) that Towny then uses to calculate it's decision using the PlayerCache/TownBlock Permissions.

It will go something like this:
1. A block broken by a player will fire a TownyPermissionEvent (name pending) with type DESTROY, the location, the player, the material, etc.
2. The TownyPermissionEvent will be caught internally by a single class made specifically to process decisions where the playercache will be consulted and Towny will decide what will happen.
3. Towny will then fire a 2nd cancellable TownyDestroyPermissionEvent.
4. The TownyDestroyPermissionEvent will be there for other plugins and Towny itself. It would contain the result that Towny has already reached. (An action that is cancelled by Towny would still fire an event, in the case another plugin or Towny wants to un-cancel it.) The final result of the TownyDestroyPermissionEvent will be fed back to the TownyPermissionEvent to determine cancellation.
5. The original block break action will then resolve based on the status of the TownyPermissionEvent's final state.

This system would enable us to remove all of the war code throughout Towny's many checks and balances. 

The code in the listeners will shrink as the only thing required is firing the correct events when blocks are built/destroyed/interacted with.

War will be much easier to code for the basic Build/Destroy/Switch/ItemUse/PVP/Explosions/Fire/Mobs events, no more trying to remember all of the places where switch/itemuse actions are being launched from.

I think this would do a fair bit of good to accomplish @Goosius1's 2nd bullet point regarding TownPerm changes.

**Comment by LlmDl** [comment]
Less than a month later and I feel like what I'd described in the above post is already well on its way. 

The [Expanding The API/War Separation project](https://github.com/TownyAdvanced/Towny/projects/16#card-47739791) is now tracking the progress on the course that Towny development will take in this regard, and in the long run I think all of the war modes will become separate plugins/modules rather than all being combined into one war system (which is why this ticket will be closed, as ultimately we won't be combining all of them together.)
