### ISSUE TITLE
Suggestion: Method(s) to mitigate spawn camping

### ISSUE THREAD

**Issue by TheFlagCourier** [TownyAdvanced/Towny#3659]
# Summary: 
Adding a method to redirect Town/Nation spawn travel to a safe nearest-neighbor plot when the spawn plot has an enemy player in or around it's vicinity, when the town/nation is at war. To protect spawn camping, and giving defenders a chance to safely warp in and assess the situation.

## Should affect:
- Town Spawns
- Nation Spawns
- Outpost Spawns
- Player bed spawns (if in-town)
- "BugOut" plots (also being proposed)

## Restrictions:
- Should not spawn a player within a building, unless the player has the appropriate residence permissions. (ceiling check, can borrow from flagwar)
- Should not drastically change the altitude of the player spawning in relative to the actual spawn location (ie: don't spawn them in a pit or on a wall)
- Living Players: Warning confirmation messages when running the `/t|n spawn` & `/t outpost [#]` commands. (If safe-check fails)
- Living Players: If no safe location is found within radius, present confirmation to teleport to real spawn; AND/OR, provide an override flag to the spawn command (`/t spawn unsafe` [may conflict if a town is named "unsafe"...] / `/t unsafespawn` / `/t spawn -F`)
- Dead players: Players that are re-spawning at a town spawn can either have a larger search radius, or be forced to use a bedspawn / world spawn.
- Additional thought: Allow towns to set a single "Bug-Out shelter" plot for re-spawning players when at-war, which can use a reduced radius, or ignore the system entirely.

## Related:
- [New spawn options](https://github.com/TownyAdvanced/Towny/pull/2771) (PR #2771)
- [Suggestion - Siegewar - Add exploit prevention around enemy/non-enemy](https://github.com/TownyAdvanced/Towny/issues/3615) (Issue #3615)

**Comment by Goosius1** [comment]
Hi Flag, 

- The requirement here is very good (e.g. prevent that camping),  
but I fear that a short-range TP could be exploited  e.g. Given 2 players, a resident A, and a collaborating hostile player B, who want to get into a building belonging to resident C (where C has switchable chests and items).  A kills B a few times, until B finally gets past the obstacle and loots the chests.

- A long-range TP meanwhile, is a problem too, because on a number of servers, both rtp and even /t /n spawning are completely disabled or restricted.

- I have an idea which when combined with yours might work well...  I propose that for detection, use exactly that method you proposed above, where the players in the vicinity of the spawning player are checked. Then IF an enemy is detected,  do something very simple: 
    1. Make the spawning player IMMUNE to pvp damage (or maybe all damage), for like 1 minute AND
    2. Ensure that the spawning player cannot attack anyone in this time.

....I believe even full damage immunity in this scenario would only be marginally exploitable, say to get past an unusual lava trap set up by another resident or something.

**Comment by Goosius1** [comment]
Hi Flag I made a branch-from-siegewar with just the above post-spawn-pvp-immunity time thing (bcs ppl are now getting slaughtered a lot during sieges😂), gonna test it this evening.

If the Tp redirect thing (or other measures) are implemented soon or later, then perhaps all the working measures could then later be combined into one even fuller solution.

**Comment by TheFlagCourier** [comment]
@Goosius1 sounds good.

I hadn't even started working on actually implementing tp redirect, yet. Just been busy and waiting for 0.96

**Comment by Goosius1** [comment]
- Damage prevention feature added, its now in the siegewar branch
- Local testing was good, lets see now if players in the trial find a way to abuse it in some way  :sweat_smile:

**Comment by Goosius1** [comment]
Temporary immunity feature seems to be working fine on the public servers. Also no reports of any exploits yet.

One thing is, that it currently uses the player invulnerability flag. So whatever the cause of this flag being true, the affected player cannot damage others.   I wonder could this potentially interfere with mod activity on the server?

**Comment by Goosius1** [comment]
FYI 
- The post-spawn immunity feature was actually deliberately removed from SiegeWar a few months ago, along with nearly all remaining direct combat effects such as healing modifiers.
- The reason was that such effects are focused on individual combat/PVP encounters, rather than the overall war, thus to keep responsibility of that particular plugin focused on more general and geopolitical concept of "War", and avoiding unnecessary code complexity, they now exist just as "recommendations" for deployment of dedicated combat/pvp plugins which seem to already support the sw-desired effects effectively.

**Comment by LlmDl** [comment]
Towny has since had spawn-protection from combat added.
