### ISSUE TITLE
waste of money (town bank)

### ISSUE THREAD

**Issue by Dauwks** [TownyAdvanced/Towny#3931]
Hello

Since a few days, cities have seen their economy reset, I use essential economy.

Thank you in advance.

### What is your Towny version?
0.96.1.0

### What is your spigot/craftbukkit version?
paper 1.15.2

**Comment by LlmDl** [comment]
Essentials and EssentialsX Economy resets your town and nation bank accounts, seemingly at random.

The EssentialsX Team doesn't recommend using their economy with Towny.

This issue has existed since MC 1.8 and onwards. [There is a ticket on their tracker for it.](https://github.com/EssentialsX/Essentials/issues/2921)

**Comment by Dauwks** [comment]
Thank you for your prompt response.
Do you have a plugin to recomended me?

**Comment by LlmDl** [comment]
TheNewEconomy, Hyperconomy, HellConomy, iConomy 5 (Towny edition), PhantomEconomy.
