### ISSUE TITLE
Suggestion: 

### ISSUE THREAD

**Issue by Baileyc889** [TownyAdvanced/Towny#3934]
**Please explain your feature request to the best of your abilities:**

Could additional town perm types be added for “kill” (killing mobs) and “ride” (horses, minecarts, etc)

My discord name is Bailey#7973

Thank you

**Comment by LlmDl** [comment]
The horse thing, cannot be done via Towny. Otherwise you'd lose your horse if you dismounted in the wrong plot. You can get horse plugins for that sort of thing.

The mob killing thing, we already handle farm animals. I don't think limiting who can kill a monster on a plot would be very fair either. Mobs who are invincible to attackers would be used to trap/attack people visiting towns.
