### ISSUE TITLE
Suggestion: Permissions to set a resident's town_block_ratio contribution

### ISSUE THREAD

**Issue by spathizilla** [TownyAdvanced/Towny#3945]
**Please explain your feature request to the best of your abilities:**
Currently a player's contribution to a town's claim limit is either based on the town_block_ratio config setting or based on the Town's level. 

My suggestion is to create a permission/meta node which will change the number of claims a player contributes to a town's claim limit - like the towny_extraplots changes the number they can claim themselves inside the town.

**Comment by LlmDl** [comment]
This doesn't really work. Towny doesn't look at anything in regards to the residents it is counting in order to determine how many townblocks they contribute. To change it, it would require us to start making permission lookups any time we need to calculate the total, which would potentially end up looking up permission nodes owned by offline players.
