### ISSUE TITLE
Town claim auto not working

### ISSUE THREAD

**Issue by Regner6** [TownyAdvanced/Towny#3949]
### What steps will reproduce the problem?
1. town claim auto
2. town claim rect auto
3. town claim circle auto
4. Even adding a 4 at the end of the command doesn't work
Anything to do with claiming auto i get this message. same with other players 
![62fe29dfe646b876ab0504efb14761fe](https://user-images.githubusercontent.com/16054126/80164973-5aa53d80-85a8-11ea-95c0-3f23891fa83a.png)

### What is the expected output?
1. invalid radius amount. use an 4 or less
2.
3.

### What is your Towny version?
Do not say "latest".
Towny-0.96.1.6.jar

### What is your spigot/craftbukkit version?
Do not say "latest".
spigot_1.15.2.jar - provided by beastnode they say it's the latest but i do not know specifically.

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/Xnifu6Mu
3. Your townyperms.yml : https://pastebin.com/rCykKka8
4. Your log's error :  None

(optional) If this is to do with permissions, 
5. Your permissions file : https://pastebin.com/VNymtZyU

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
I looked into this and this command `/town claim auto` requires the permission node `towny.command.town.claim.town.multiple`. 

The commands `/town claim circ auto` and `/town claim rect auto` do not exist. Instead of using auto you must provide a number which is the radius of the space you want to claim. Ex: doing `/t claim rect 4` would claim a 7x7 chunk area surrounding you.

/t claim auto, /t claim circ and /t claim rect all require the above permission node. This was done because too often people were using /t claim auto|rect|circ while they had hundreds of plots they could claim and it would cause their server to crash.
