### ISSUE TITLE
Towny economy

### ISSUE THREAD

**Issue by alex17lol** [TownyAdvanced/Towny#3974]
If im creating an economy plugin to work with towny how do I do it because I heard that towny uses fake players for things like banks. basically I need to make integration with towny and my custom eco plugin

**Comment by LlmDl** [comment]
You need to accept the older, deprecated Vault methods that use strings instead of UUIDs. You can see examples of what Towny uses in the [TownyEconomyHandler](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/TownyEconomyHandler.java#L140).

You can also interact directly on Towny accounts via Towny's [EconomyAccount](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/object/EconomyAccount.java) object which Towns, Nations implement.
