### ISSUE TITLE
Suggestion: Mayor command to give plot specific permission based on citizen's rank (FTAO -> F"R"TAO)

### ISSUE THREAD

**Issue by kekke3r** [TownyAdvanced/Towny#3993]
It would be great if the mayor of a town could set perms in a specific plot not only for the FTAO macro groups but also for the server specific admin created ranks.

The "T" group can appear to be too generic sometimes and can be enhanced by adding this feature, by doing so the rank system will not only grant the possibility to control every citizen permission to perform or not certain commands but can also be used to decide in what plot a player with a specific town rank can or cannot perform certain actions.

For example in my server every mayor can grant to a player in his town a rank for the job he want to do to help the town by gathering materials or simply making money; with this feature a player with the rank "farmer" could be given permissions to gather materials in the town's farm plots (i'm aware that there is a  option to set the plot as farm type but it isn't "rank selective") or a "miner" can be added to a plot where a mountain needs to be destroyed. A "banker" can recieve switch permissions in the bank plot and so on.
The plot buying is limited to the player who claim it and the plot permissions can be sometimes too generic because at most they are bound to the Town context so this feature offers a middle ground so maybe the FTAO can become the FRTAO

As an alternative of what i have written before it could be implemented a system to grant the server's admins the ability to create their own plot types with their own permissions and nodes. This way they can add the permission for a specific plot type to a certain rank.
Example:
The plot type "Mine" is created in the configs
Upon creation the permissions town.plot.mine.switch, town.plot.mine.build ...(etc.) become available
The permission town.plot.mine.build is granted to the custom rank "Miner"
Now all the players in a city that have the rank Miner everytime a plot is set to "Mine" can build inside that plot.

**Comment by LlmDl** [comment]
Customizable plots using permission nodes has [a ticket](https://github.com/TownyAdvanced/Towny/issues/370) on here already, it's just not something that's been done because it will likely cause issues.

That aside, we already have an R for the perm line of Town-owned land, RNAO. 

I am not entirely sure how we would bridge the plot types and the ranks who would have the ability to work on them. If the rank and the plot type had the same name that could work but it would mean non-English servers would have to have some English ranks.

Most servers/towns are not blocking their town members into jobs that can only work in specific areas of their town. Most are using builder ranks that have the towny.claimed.townowned.* permission node, so mayors can promote trusted members to work in town-owned land.

**Comment by kekke3r** [comment]
I understand, anyway thank you for the advices, I will try that way and close this issue. Wish you all the best in your work!
