### ISSUE TITLE
Town creation results in Internal Error

### ISSUE THREAD

**Issue by Cravis44** [TownyAdvanced/Towny#4103]
### What steps will reproduce the problem?
1./t new test
2./res
3.

### What is the expected output?
1.An internal error has occurred while attempting to perform this command
2.An internal error has occurred while attempting to perform this command
3.

### What is your Towny version?
Do not say "latest".
0.96.1.0 for 1.13

### What is your spigot/craftbukkit version?
Do not say "latest".
1.13.2

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log :https://pastebin.com/D7RCTZQv
2. Your Towny config.yml (if using MySQL please remove password,): https://pastebin.com/gF6sq86D
3. Your townyperms.yml :https://pastebin.com/npZzrJUG
4. Your log's error : https://pastebin.com/UMP0TYMp

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

**Comment by LlmDl** [comment]
Your gringott's is failing. You are on the latest release of Towny for 1.13, but Gringott's semi-recently made changes to accomodate changes we made in the pre-releases which have come out since 0.96.1.0.

You may still be able to use Gringott's if you get a slightly older version. You will be able to update Gringott's to latest when 0.96.2.0 for 1.13 is out.

**Comment by Cravis44** [comment]
,You're a godsend. Thank you so much.
