### ISSUE TITLE
Question: How to disable reseting town/nation balance when doing a reload

### ISSUE THREAD

**Issue by spidertyler2005** [TownyAdvanced/Towny#4271]
When ever I do /reload town balance gets reset, is there a way to disable this?

**Comment by LlmDl** [comment]
Essentials/EssentialsX Economy is Not Recommended.
Essentials and EssentialsX Economy resets your town and nation bank accounts, seemingly at random.

The EssentialsX Team doesn't recommend using their economy with Towny.

This issue has existed since MC 1.8 and onwards. [There is a ticket on their tracker for it.](https://github.com/EssentialsX/Essentials/issues/2921) It happens because EssentialsEco doesn't reliably assign the same UUID to fake player accounts. [There is a ticket on their tracker for this as well.](https://github.com/EssentialsX/Essentials/issues/2490)

Towny has been warning you about this happening in your startup sequence found in your latest.log.

**Comment by spidertyler2005** [comment]
hmm what would you recommend using

**Comment by LlmDl** [comment]
TheNewEconomy, Hellconomy, iConomy5, or pretty much any plugin that uses Vault or Reserve.
