### ISSUE TITLE
New towns are bankrupt

### ISSUE THREAD

**Issue by KarlosWGeek** [TownyAdvanced/Towny#4426]
**### What steps will reproduce the problem?**
1. Install Towny 0.96.3.0
2. Create a Town
3. Town is bankrupt, nothing will change this

**### What is the expected output?**
1. Install Towny
2. Create a Town
3. Town has no funds, but is NOT bankrupt

**### What is your Towny version?**
0.96.3.0

**### What is your spigot/craftbukkit version?**
Paper 1.16.3 build 255

**### Please use Pastebin.com to link the following files:**

1. Your full server startup from the logs\latest.log : https://pastebin.com/SZSwmmbk
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/XHWPTQNV
3. Your townyperms.yml : https://pastebin.com/NfcMf57q
4. Your log's error :

**Comment by LlmDl** [comment]
I've never heard of frConomy. This will likely be some quirk in it. 

When Towny creates a debt account for a town it also makes sure to set the balance to 0 in case the economy plugin would try to give a default starting balance to the debt account.

Since Towns cannot be bankrupt unless their debt account is non-zero, I'm guessing you eco plugin is somehow circumventing us initializing the debt account to 0.

**Comment by sexibatka** [comment]
Ok so i use a plugin called PhantomEconomy it was a great plugin the first time i used it like 6 months ago but the last time i used it together with towny all towns started with -50$ and we also had 0 debt and i fixed it by going into the plugin's config file and setting the default starting value of a player to 0 fixed it and i think that something has changed with towny in the last 6 months that fucks with the economy plugins

**Comment by LlmDl** [comment]
@sexibatka we have changed some things this year with how economies are handled.
