### ISSUE TITLE
Suggestion: Checking the permissions of an offline player.

### ISSUE THREAD

**Issue by GenericEntity579** [TownyAdvanced/Towny#4616]
Hey there,

My server has run into some compatibility issues with Towny and Slimefun, the most pressing for the players being Slimefun mining androids. Slimefun mining androids are basically custom heads that move around and do specific tasks they were programmed for, as they operate they consume fuel. The issue occurs when the owner of an android goes offline, the android continues to move around and consume fuel, but it is unable to break blocks. 

How it was explained to me is that Slimefun does permission checks each time an android breaks a block, to make sure the owner is allowed to break blocks in the area that the android is in, and Towny does not support permission checks of an offline player. When the plugin does it's permission check, and the owner of the android is offline, the plugin receives an automatic false on the check and the android is not allowed to break the block.

The point is, if Towny does indeed not support permission checks on an offline player, would it be possible to add support?

_I was also directed here by a Slimefun dev: https://github.com/Slimefun/Slimefun4/wiki/protection-plugins#adding-support-for-your-protection-plugin_

Thank you,
And Happy Holidays 😄

**Comment by LlmDl** [comment]
Not saying it won't happen some day, but I am fairly busy with other things already.

**Comment by stanier** [comment]
https://github.com/TownyAdvanced/Towny/blob/e986b4ca638491e35293f47701a6cd190658eb61/src/com/palmergames/bukkit/towny/Towny.java#L590 looks like the culprit to my untrained eyes.

I think that it's silently failing to create the cache for an offline player because it's asking the world coordinator which town block the player is in when they are actually offline.  Maybe if there is a way to bypass this, or have an offline-friendly cache creation function?
