### ISSUE TITLE
Towny conflicting with GemsEconomy

### ISSUE THREAD

**Issue by EddieDiamondFire** [TownyAdvanced/Towny#4704]
### What steps will reproduce the problem?
1. Install GemsEconomy 4.9.2
2. Install Towny 0.96.6.0
3. Run the Server
4. Now execute /town new <Town Name>

### What is the expected output?
1. It should return no error with Town Accounts.

### What is your Towny version?
0.96.6.0

### What is your spigot/craftbukkit version?
Paper version git-Paper-"36d7de3" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Please use Pastebin.com to link the following files:
Console Log:
https://pastebin.com/FkJsFEiS

Config.yml (I cannot upload this to pastebin.com due to an error sorry):
https://sourceb.in/YKYMlTpevg

Townyperms.yml:
https://pastebin.com/ESDVmU1D

Log Error (None):
https://pastebin.com/ABDs0PtC

Notes:
- I'm using a host provider called Minehut, therefore I cannot update plugins and/or update the server jar.
- I have talked to the developer of GemsEconomy. They said that Towny is not using the correct api for vault.

**Comment by LlmDl** [comment]
GemsEconomy needs to support the old Vault methods if you want to be able to use it with Towny. There's actually a PR on here with the recent efforts to modernize our vault api calls but its probably not going to happen for a bunch of reasons.

Economy plugins don't have a reason to not support the old vault methods as they will never be removed and there's no suitable way to make fakeplayer accounts otherwise.

**Comment by LlmDl** [comment]
Actually looking at their source, they do have the old vault methods. I don't know what they're doing which prevents Towny making an economy account for the town in GemsEconomy though.
