### ISSUE TITLE
Suggestion: Automated plot evict for sale

### ISSUE THREAD

**Issue by SeanSean98** [TownyAdvanced/Towny#4892]
This suggestion is meant for servers without the towny war plugin/mechanism.

As a Mayor, but also as Town Staff it is very annoying having to set plots for sale every time someone is evicted due to insufficient funds. That's because once someone is evicted the plot return to the town's property (aka no plot owner).

Could it be possible to have a config in which the server is able to toggle the evicted plots to be set for sale at the default plot type price immediately after being evicted? This would make the work of Town Mayors and Staff much easier and it holds the possibility for residents to repurchase their land or even compete to get someone else's.

Eitherway it would only be available if the Server Owner enables the config.

**Comment by LlmDl** [comment]
So when a player leaves a town they have all of their non-embassy plots go up for sale at the town's default plot price.

If a town has a tax on their residents and the resident could not pay they would be kicked from town and all their plots go up for sale in that scenario as well. 

But since the player hasn't left town when plottaxes take their land, they do not have their land go up for sale.

A new config option does make sense here I think.
