### ISSUE TITLE
Suggestion: Make `res toggle plotborder` show smoke on the tops of all blocks in the plot (not just the surface)

### ISSUE THREAD

**Issue by MilesBHuff** [TownyAdvanced/Towny#5085]
**Please explain your feature request to the best of your abilities:**
Please make `res toggle plotborder` show smoke on the tops of all blocks in a plot.  Right now, smoke only appears on the topmost block;  and this makes the command completely useless in the Nether or in caves.

**Comment by LlmDl** [comment]
Part of why its on the tops of blocks is because Bukkit can tell us exactly what the upper most block is in one 1x1 space. This means we can quickly put smoke on the 60 blocks we need.

If we did what you're asking for we would be going through the entire strata of a townblock's walls, putting smoke on every solid block we find, which could be up to 60 per y level. This is probably slow, probably laggy for the client and could hammer a server if someone was using /res toggle constantplotborder. 

F3+g does what you want if you use a town_block_size: 16.

**Comment by MilesBHuff** [comment]
Thanks for the quick response and good explanation.
