### ISSUE TITLE
Suggestion: Add progressive upkeep for peacefulness

### ISSUE THREAD

**Issue by Jqnnies** [TownyAdvanced/Towny#5411]
**Please explain your feature request to the best of your abilities:**
I would like to recommend adding an option for peaceful towns to have progressive upkeep, this is because some towns simply just go peaceful just to hide in them, so it would make more sense for a large town to have a higher peaceful cost depending on the amount of residents it has.

**Comment by Goosius1** [comment]
By coincidence I was commenting on a server recently on the town-peacefulness-cost, and, for what its worth here is my view, as summarized in my post there:

**RECOMMENDATION**
- In server setups where *SiegeWar* is running, it is recommended to disable the town-peacefulness-cost completely.

**BACKGROUND**
- On some servers, some players/staff believe that nations should be able to tightly control their claimed area, using sieges/siege-threats to get what they want. Thus, Peaceful towns are seen to be "hiding" from rightful control by nations.
- Setting a a town-peacefulness-cost increases nation-area-control, because since casual players cannot afford the extra cost, it ends up that fewer peaceful towns exist.

**PROBLEM**
This solution doesn't work:
1. Kings are STILL unable to control the area. Peaceful towns containing dedicated players cannot be forcibly controlled or removed.
2. For casual "builder" towns in regions dominated by good kings, this is ok, except they are forced into doing diplomacy which they don't want to do and are not good at.
3. For casual "builder" towns in regions dominated by bad kings, this seems like a big problem!!!. These towns, having no realistic option to escape local control, are forced to endure unjust, nasty, and toxic influences. They might get toxic themselves, leave that part of the map or just move to a different server (and remember, there are many servers where playing in a peaceful style is completely free!)

**SUGGESTION**
- Set `price_town_neutrality` to 0 in the Towny config
- Increase nation-area-control in a positive way, by adding the *TownyResources* plugin. This plugin gives kings a regular flow of resources from all their towns, including occupied peaceful ones!.

**Comment by Vaspei** [comment]
I upvote this
