### ISSUE TITLE
Suggestion: Add the wild regen explosions to towns

### ISSUE THREAD

**Issue by Peskdt** [TownyAdvanced/Towny#5774]
### **Please explain your feature request to the best of your abilities:**

Add these options to towns plots. Would be good to have interaction with plugins like "cannons". Making sieges possible with minimal damage to valuable buildings.

![imagen](https://user-images.githubusercontent.com/91406867/155841177-f572f64c-6e69-4e4e-9f6e-1790fcbecda8.png)

**Comment by LlmDl** [comment]
SiegeWar has the Cannons plugin integration tied to the new Wall Breaching feature.

It doesn't regenerate things but that's sort of the point.

EventWar does have explosion regeneration in towns.

I haven't put it into Towny itself because it's inherently unsafe to allow explosions in protected areas and expect them to regenerate correct every time. The EventWar implementation is not a perfect system and there are minor side effects.

**Comment by Goosius1** [comment]
Fyi In SW, Cannon Sessions are gone now, the mechanism is completely refactored (see the latest pre-release).

**Comment by LlmDl** [comment]
> Well, the siege war integration allows the cannons only in cannons sessions. I didn't know that EventWar exists. But the use I wanted to give it is for mechanics like:
> 
> * blow up the jail of a town freeing the convicts without the need to declare war by a country. (Assuming in a role server where penances can range from many hours to permanence).
> * allows external armed groups that do not qualify as a nation to attack cities.
> * Momentarily penetrate structures so that citizens do not take shelter in a building avoiding pvp.
>   Well maybe this is very accurate for a type of hostile rpgs servers.
>   I'll try event war. How can I get it?

EventWar is available to my Sponsors.
