### ISSUE TITLE
Suggestion: Allow for certain plots to be put up for sale OR create a default town plotlimit. 

### ISSUE THREAD

**Issue by ghost** [TownyAdvanced/Towny#5944]
### **Please explain your feature request to the best of your abilities:**

Greetings Towny Devs and Towny Community,

I was playing my new favorite Earth Minecraft Server, EarthMC and I realized the potential for a new feature that pertains to a trust.

First, the issue; Town Members with the ability to put plots for sale can put any plot that is unowned for sale and any new town member can claim that town plot. This creates an issue where you can't place multiple plots for sale and leave them there because any member can claim all of them.

I had two solutions:

1.  Allow the Town Mayor to designate a number of plots a certain user can claim. Perhaps something like `/t set plotamount <user> <int>` and this will allow that user to claim <int> number of plots and by default it can be set to 1. This will allow a mayor to put up multiple plots up for sale without the fear the entirety of the free plots can b claimed by one user.

2. Create a tag for plots that can be assigned to the plot to allow someone like a Recruiter (with a new permission) to assign only those tagged plots for sale. This steers the interaction from automated to direct contact but it allows the Mayor to have more control over what plots can be put for sale besides just any plot. 

In my opinion, Option 1 is easier but Option 2 allows for more control of town design and plot layouts. 

An argument against this could be the fact Town Mayors or those with permission can just assign one plot for sale at a time; but availability isn't always the best in my experience and this causes a retention issue for both the Server losing a player and the town losing an active member.

If you have any questions, you know where to find me.

**Comment by LlmDl** [comment]
This is already half-way available:

The max_plots info node (and the analogous towny.max_plots.# node) are already able to limit the players to a specific number of personally owned plots.

If you set these nodes in your townyperms.yml nomad at 1 or 2 you will limit every player to 1 or 2 personal plots, and then if you'd like you can make town ranks with progressively higher towny.max_plots.# nodes, so that mayors can give some of their residents the ability to claim more.

What we don't have is a system of pre-assigning plots. I could see this being very useful but I don't know if it should still require the player to claim them. If they're being assigned a plot should the mayor/assistant not just give them the plot directly?

It's also worth noting a discrepancy: by default Town Members do not have the ability to put plots for sale, only players with towny.command.plot.asmayor can put a Town's plots for sale.
