### ISSUE TITLE
Suggestion: Ability to over claim

### ISSUE THREAD

**Issue by FixTheAdmin** [TownyAdvanced/Towny#6564]
### Feature summary
Allow over-claiming chunks owned by a town that is larger than it has residents to support. 
![image](https://user-images.githubusercontent.com/12761593/224735211-4811f5c8-1b71-4503-a875-e0340fd266c6.png)

### The problem
I run a very large Towny server on a limited sized map. Players spam invite residents in order to increase their claim bonus. Once invited, residents are disregarded and the town uses the additional bonus to maximize town size. Residents eventually leave or become inactive but the town size remains. This leads to large but empty ghost towns that take invaluable land which could have been used by active players. Mayors of these towns make sure to sign in every once in a while so that the town doesn't get deleted due to inactivity, essentially squatting land from the active player base. 

![image](https://user-images.githubusercontent.com/12761593/224747327-72503e3a-841f-49d3-b450-b8f063f7f461.png)

### Benefits of an over-claim feature
- Mayors shift focus from maximizing town size to developing and building the land already claimed. 
- Mayors will only claim the land they need which in itself should open up the map more.
- Mayors can expand their active town at the expense of the inactive neighbor.
- Mayors are incentivized to keep residents instead of only focusing on inviting them. This should improve gameplay expeirence for residents.
- Lowers the need for map resets with more dynamic town and nation size gameplay.
- Resident activity, instead of mayor activity, equals nation/town power. 
- Towns in less contested areas can still remain larger than their current claim bonus as others are less likely to want the land. This would give mayors reason to settle towns more spread out on the map.
- A "claim decay" system for inactive towns has been proposed before. An over-claiming feature is better as claims will only "decay" if the opposing town has a need for the claim.
- Would mostly prevent the practice of claiming just to block expansion of other towns. Claim placement would need to be more deliberately chosen as claiming too much could put the town at risk of being over-claimed in the future.
- Mayors would be incentivized to unclaim chunks themselves in order to protect chunks that are more valuable to them. This should also free up more space in congested areas.
- Would remove the need of forcing mayors to remember to sign in every x days in order to keep their town alive. Their town will thrive as long as its residents are active.
- The feature is easy to grasp and explain to players.
- Could be viewed as a war feature. Most active town wins. Towns at reasonable size compared to their activity are protected.
- Towns are more likely to merge their efforts. Residents currently leave and create their own town as soon as they have the economy to do so.

### Considerations
- The recently introduced feature to combat "claim arms" would prevent towns from claiming a straight line in to other towns for the sole reason of stealing their items.
- Over-claiming should be denied if it would result in the town getting split in to two parts. 
- New towns can not be created on already claimed chunks.

**Comment by DeividasDavidavicius** [comment]
This would create chaos, most big towns only have a few residents. Also, if a town had exact amount of claims as resident+nation bonus, and a resident left the town or got removed for inactivity, other towns could overclaim it immediatelly and claim most valuable chunks (like the ones containing storage or shops) and steal all the items or blocks.

**Comment by DeividasDavidavicius** [comment]
This would create chaos, because people would just use townless invite all constantly to always have more res than claims so that they dont lose them, so expanding towns would be super hard. Also, most big towns have wayy less resident claim bonus than claims.

**Comment by MonarchTai** [comment]
I really like the idea, myself a recruiter, stuck in the middle of Britain with Inactive towns all around me. I need some sort of way to expand. I have been sitting at around 200/920 chunks for the last few months. 

Maybe also add a higher max claim limit so other towns can keep expanding at max claims. So for example, you pay 16 gold to buy a new plot. Then you pay another 16 gold to claim that plot. So you're paying 32g for a new plot while being over the max. 

I really hope you go through with this idea!

**Comment by DSDevil** [comment]
I would pefer if any plots that are over the limit are automaticly unclaimed once every week from town border.. Like town ruins but for chunks

**Comment by LlmDl** [comment]
This suggestion is made by a Sponsor. If you like my work and want to have an influence on development you should sponsor too.

https://github.com/TownyAdvanced/Towny#a-special-message-from-llmdl-precedes-the-normal-readme-

**Comment by Aylywyn** [comment]
If this is implemented, I'd like to see this as well: https://github.com/EarthMC/Issue-Tracker/issues/1601.  Link to the EMC Issue but a cut and paste follows.
-----
[Claim Limit Increase/New Gold Sink/"Fillager"]
#1601
Is your feature request related to a problem? Please describe.
Some people do not like to recruit and/or deal with too many town members. A method for raising the Claim Limit may be desirable. Inflation can be an issue. A new gold sink will be a side benefit.

Describe the solution you'd like
The ability to purchase an NPC Town Member for your town in order to get the extra 8 chunks of claim limit. Essentially spending gold on a villager to help fill you claim limit cap, a "Fillager" if you shouldn't. A cost of 256g would basically triple the cost of an over-claim limit plot, adding 32g per plot; while a 128g cost would double it to 16g plus 16g.

Additional context
Provides a way to Mine, Vote, Shopkeep, or Hunt your way to a bigger town (or Buy Mystery Crates and Sell Player Heads...) over the need to recruit bulk inactive players just to cap out.

Gives another Gold Sink to slow server inflation.

Possibly (though inching towards P2W) gives the chance to add, say, "1 Free Fillager Per 3 Months Premium".

Preferrable, IMO, to a simple Over-Limit charge or Towny Bonus Claim as it shows up in Population stats to compare towns and gives an obvious sign that a town is purchasing land over recruiting.
-----
256g might be a better choice for balance as things inflate.

**Comment by Colt44Magnum** [comment]
Wouldn't this just make more people spam recruit? I do think this will increase player retention on servers but that actually falls into the hands of the mayors of the towns. There are some towns that mass recruit just because they can, looking more at trying to get as many residents as possible. Thus population ≠ player retention. 

I once owned a town that was completely surrounded and had to use diplomacy in order to purchase towns around me to claim their land into my own town. That is a dynamic of the game that will be lost completely. If mayors are still coming online every x amount of days you can send a mail in order to interact with them. I know for some issues where towns are surrounded by friendly towns and could purchase those from their friendly towns if claims are an issue. 

This might also just incentivize towns to stay as single resident towns and max out their towns claims to the claimbonus. While this could possibly decrease overall nation size, only one city would be needed to spam recruit so that all towns within the nation could spread out as far as possible. Then you just have smaller but multiple mayor only towns logging on every X amount of days to keep the land from falling. ( If you have friends this would work :sob:) 

This could also just lead to towns claiming out further and then only developing the center of their town. This way they would be able to keep their main buildings safe from the towns around them claiming in. What happens when an active resident owns a home on the outskirts of town but then their plot gets claimed by a surrounding town? This could result in a snowball effect where players leave the town or completely quit the server. Spam recruiting residents and not giving them a plot seems to be a good solution to residents getting mad because they lost their home. 

I think overall this would be an interesting feature to allow servers to mess around with. Increasing player retention even by a few is good for servers (and can help increase revenue of said servers) Everything can have its own cons but that shouldn't keep plugins from developing new features that might help servers grow in the future.

**Comment by asyi0** [comment]
I think If you want to add overclaiming on a server where you don't want the devastation caused by the war plugin, it should be only possible against towns that are really inactive but occupy a large area.
For that, it should require a high time/gold cost to overclaiming, and the defender should be able to easily prevent it at a low cost as long as you are active.

Here are my suggestions to make it happen
- Base overclaiming cost is 4x higher than claiming wilderness
- After the overclaiming, there is a 72-hour grace period between the execution of the command and its completion. The defender can disclaim the overclaiming by paying 1/2 of claiming wilderness cost during the grace period.
- A town only can overclaim 1 chunk at a same time.
- To prevent claim arms, the gold cost of claiming/canceling varies depending on the belonging of chunks surrounding the target chunk. The more chunks adjacent to the target chunk, the more advantageous the town is.
  - Example: If the surround of the target plot is such that 3 chunks are owned by the attacker and 5 chunks are owned by the defender, the cost is (4+(5-3)*2) = 8x higher than claiming wilderness.
If attecker has 5 and defender has 3, the cost is (4 - (5-3) * 1/2) = 3x higher than claiming wilderness

**Comment by FixTheAdmin** [comment]
Nice progress!

In my personal opinion, I think the same claim command `/t claim` should be used when overtaking claims. Towny already has a lot of commands and it can make sense from a user experience perspective to consolidate commands that does the same thing.

**Comment by FixTheAdmin** [comment]
On another note, I also think that players with ability to claim should be notified in chat if they stand in a chunk that can be taken over/overclaimed. Giving hints in-game is useful for those that don't look up towny docs, which I suspect is the vast majority on most servers.

**Comment by trybd369** [comment]
Isn't it indeed a pity for the players who have been working so hard?
Some may have set aside land to build large buildings, and it is to the server's detriment to lose them.
Many well-known players will retire.
I think that only inactive lots with no buildings and no residents should be ticketed and be deletable.
And the ticket should also have a condition such as "obstructing a nearby active town".


Translated with www.DeepL.com/Translator (free version)

**Comment by LlmDl** [comment]
I started out with it using /t claim, but its just a pile more code to mesh together.

Making a notification to entering plots is probably very easy and it can suggest the right command, which will lower the confusion.

**Comment by LlmDl** [comment]
> On another note, I also think that players with ability to claim should be notified in chat if they stand in a chunk that can be taken over/overclaimed. Giving hints in-game is useful for those that don't look up towny docs, which I suspect is the vast majority on most servers.

I've coded this but I'm not sure how strict it should be.

1. Should it be shown to any player with a town that has available claims, when they're travelling from any plot that cannot be stolen into a plot that can be stolen, or
2. Should it be shown only to a player that is moving from their own town (which has available claims,) into a plot that can be stolen that directly borders their town. (Only showing the notification when the player could actually use `/t takeoverclaim`.)

**Comment by CorruptedGreed** [comment]
> I've coded this but I'm not sure how strict it should be.

I think the 2nd option would be optimal and have the most utility to players. The 1st option's function could easily be deducted from checking the town's /t and seeing that they do not have enough claim limit. This may also cause confusion to players who believe they can overclaim the immediate chunk(s) due to being notified.

The 2nd option would allow for a direct inform->action potential. Players are made aware of land they can immediately access due to overclaim, and as a result can choose to overclaim it on the spot there as a part of their town using the command.

**Comment by LumberJackie09** [comment]
I and many of my friends will leave or move to small islands if this gets implemented. I will refund my premium personally. Please listen to the community, fix. (P.S. please fix the mod team)

**Comment by creatorfromhell** [comment]
> I and many of my friends will leave or move to small islands if this gets implemented. I will refund my premium personally. Please listen to the community, fix. (P.S. please fix the mod team)

Please use a different forum for posting about specific servers. This is for the Towny plugin only, which is used by numerous servers.

**Comment by 0xBitMC** [comment]
While I agree this suggestion would be a nice feature if improved upon, there is some things that needed to be considered. 

- How will you handle a group of residents leaving their current town due to various reasons and over-claiming their previous town with a new town? 

If enough residents left their town, this would put the town into the over-claimed territory and cause their town to be subject to being taken oven. 

- How will you prevent straight line claiming? 

Clearly, if you are the one trying to claim over someone else's territory, your goal is probably aimed at extracting value. What mitigation will be in place to prevent towns from being torn apart easily. 

CorruptedGreed mentioned `town.min_adjacent_blocks`, to expand on it, there should be a minimum radius that is protected at the Homeblock and any Nation spawn. In addition, you could use the similar code that checks if a Siege Banner is in a proper border claim to place the banner. This code could be used to allow claiming-over only from the border, preventing immediate inward claiming. In the attached image, I drew a red-line as an example of a proposed requirement to allow claiming-over only from the border:
![image](https://user-images.githubusercontent.com/101461932/229988481-b75281c4-95e3-4786-b895-5cd274a03b5b.png)

In alternative to this suggestion would be instituting a flag on over-claimed plots that would prevent certain actions in those claims, such as build/destroy from any residents. Similar to the feature that prevents action from towns in debt-cap. These flags could be recognized in API allowing developers to determine actionable events in a plot and decide cancels for further penalties, like preventing shops from working in those claims and etc.

**Comment by Twitchyyy** [comment]
I'm completely against it on principle.

But if it is to be a thing, there needs to be safeguards for the ways players can abuse and exploit the mechanic, like 0x's suggestion, because players are really good at that.

There's the possibility of players mass-leaving a town, or someone getting baited into doing /t purge

There's also the possibility of organized groups of players _mass-joining_ a town. This system would make residents literally worth their weight in gold. An organized group of players could leverage that fact and "hire out their services" to towns - joining them so they can claim over a rival. **It would be a very lucrative meta lol.**

Maybe something like a timer until a town can use a newly joined resident(s) towards chunks they can claim from an overclaimed neighboring town? Having that at least take a while for you to be "established" in the town before they can claim over might at least make that kind of group hopping not worth the time. 

I'm completely ignorant when it comes to the actual coding part so idk how feasible it is but my main point is all the ways that players can abuse this mechanic and exploit it needs to be considered in exhaustive detail before something like this can be added.

P.S. _Almost forgot this as well since EarthMC does not have them as a feature, but how do outposts feature into this? Would they be able to claim over towns or vice-versa?_

**Comment by LlmDl** [comment]
Everything is done now, but there is one caveat:

It is possible to split a town into two sections, but it is not possible to do so with a single-line of claims.

It becomes possible when your "arm" of townblocks is 3 plots wide.

**Comment by LlmDl** [comment]
I believe I figured out a graceful way to prevent a town being cut into two sections. Requires testing but things are looking fairly solid.
