### ISSUE TITLE
Bonus claims issues

### ISSUE THREAD

**Issue by BlueFyreMatt** [TownyAdvanced/Towny#6589]
### What steps will reproduce the problem?

Users who purchase bonus claim chunks have no way of selling these chunks. This creates problems down the line when they want to merge their towns as the bonus chunk cap prevents towns from merging, and they have no way of selling these bonus chunks back to the server.

This can be seen by having one town accept another towns merge request where their cumulative bonus chunk count would exceed the bonus chunk cap.

### What is the expected output?

The user should be able to sell their bonus claims back to the server for either a partial or full refund, probably a configurable amount based on a perfentage?

### Towny version

0.98.6.0

### Server version

1.19.2

### Please use Pastebin.com to link the following files

N/A for this issue type

**Comment by LlmDl** [comment]
This one is actually usually just an issue with how the default town_level limits townblocks. The townblocklimit should be keeping pace with the numResidents but it doesn't, which is why two towns combining's future town_level doesn't have enough townblocks, or their combined purchasedTownBlocks are above the future town_level's townBlockBuyBonusLimit.
