### ISSUE TITLE
Suggestion: special switch perm while in Spectator gamemode

### ISSUE THREAD

**Issue by Wextra** [TownyAdvanced/Towny#6828]
### **Please explain your feature request to the best of your abilities:**

As it stands right now, moderators that aren't in OP can not open chests, furnaces and such in towns even if they are in spectator mode or vanish (SuperVanish). After a discussion with llamadeal I was asked to file a suggestion asking for a special permission regarding switch perms while in Spectator gamemode. Doesn't have to be exactly this though, but something that means that spectators can open chests, furnaces and so on.

**Comment by Warriorrrr** [comment]
I'm not really sure about this, since we'd then need to add protections for removing items from containers which could get a bit complex/unreliable. Another idea would be to open an immutable copy of the container for the player but that seems more like something that should be done in a small addon plugin.

**Comment by LlmDl** [comment]
Are these moderators going to be able to switch from survival to spectator mode at will?

The code for this would just be listening for a TownySwitchEvent and then if it was cancelled, and the player is in Spectator mode, we un-cancel it.

The other option is just give the players who can change to spectator mode, the towny.claimed.alltown.switch.* node.

**Comment by Warriorrrr** [comment]
https://luckperms.net/wiki/Context
