### ISSUE TITLE
Suggestion: Limited amount of ranks per town/nation

### ISSUE THREAD

**Issue by Caleston** [TownyAdvanced/Towny#7028]
### **Please explain your feature request to the best of your abilities:**

**Add an option to limit the amount of each rank in town/nation.**

This will prevent towns/nations from giving out too many ranks or trust, it is a bit ridiculous that a small town could have 30 trusted players or a small nation having 10 Generals etc. 
It would allow us to give more special permissions to ranks if we could limit how many ranks are available, as now town/nations could just promote everyone to every rank and it gets very messy.

**Comment by tomhmagic** [comment]
I'd like to see this feature. I have created many small ranks to help divide the workload of running a town, so would be good to restrict the mayors to have to choose the right player for each job, rather than giving them all loads of ranks. If you can also make it so some ranks can bypass this restriction that would be good (a bool in the rank would do).

**Comment by Warriorrrr** [comment]
This is something that would be better suited for an addon plugin instead of being added to towny itself
