### ISSUE TITLE
When you use /t deposit, only the money disappears

### ISSUE THREAD

**Issue by mtmtyu** [TownyAdvanced/Towny#7064]
### What steps will reproduce the problem?

1.Use the command /t deposit 100
2.The bank balance is still 0

### What is the expected output?

The balance is reflected in the town bank.

### Towny version

0.100.0.0

### Server version

1.19

### Please use Pastebin.com to link the following files

1. Your full server startup from the logs\latest.log: [](https://pastebin.com/xVA4R5rt)
2. Your Towny config.yml: https://pastebin.com/kN9Znc4L
3. Your townyperms.yml: https://pastebin.com/LxwC71xT
4. Your log's error: 

We have introduced an economic plugin called Jecon.
https://github.com/HimaJyun/Jecon

**Comment by Warriorrrr** [comment]
Issues like these are not caused by towny, but by the economy plugin not properly handling the old string based vault methods that towny still uses. The plugin in question attempts to map every string to a uuid by looking it up, which will obviously fail when creating a new account (https://github.com/HimaJyun/Jecon/blob/27c0c9d39a4730c9c64082971f0f899d0be2b199/src/main/java/jp/jyn/jecon/VaultEconomy.java#L143)
