### ISSUE TITLE
[EventWar] Suggestion: Cause conquering to occur when a war is ended because of time, and points determine the outcome.

### ISSUE THREAD

**Issue by LlmDl** [TownyAdvanced/Towny#7216]
### **Please explain your feature request to the best of your abilities:**

Currently only riots and civil wars allow for this.

**Comment by mcmixlandnet** [comment]
Could you make a time system for EventWar, so that you can get points during a kill at a certain time (similar to the combat session system).

And a system of conquering the city after the time is up who has more points wins. Works only in Town vs Town. That the city to the winner of the war (if you attacked) will be given the city. 

Let's say town A attacked town B. As a result, the city A gained 400 points during the war, and the city B gained 300, so the city A won and got the city of the loser, well, and if the defenders won, then nothing happened.
 It would be cool, of course, to make a system of reparations, so that the attacking city's balance was removed by 20 per cent if they lost in the war and these 20 per cent were transferred to the treasury of the winner.

**Comment by LlmDl** [comment]
The time system I believe you are describing is already planned and is being tracked here: https://github.com/TownyAdvanced/Towny/issues/7211

The system of conquering-after-timed-win will be applied to across all war types, with each one having the option to turn off conquering.

I'm not sure about making it so that defenders do not conquer the attacker. That seems like a large disadvantage. Attackers do not suffer any real danger except money, while defender's towns can be wiped from existence.
