### ISSUE TITLE
[EventWar] Suggestion: Custom War Names

### ISSUE THREAD

**Issue by DarioMavilia** [TownyAdvanced/Towny#7229]
### **Please explain your feature request to the best of your abilities:**

Allow players to input a custom name for a war upon creating a declaration. They would be presented with the option to either use a dynamically generated name via the config options or to type in their own input.

As a side suggestion, maybe allow this feature to be used on all war types. I know my playerbase specifically would like a lore option to distinguish riot wars as a coup, uprising, etc, just very nice for flavour.

**Comment by LlmDl** [comment]
I have been trying to work out how the name would get entered, because it has to be entered in before the war is created internally. If it wasn't the lore books would all be mis-matched and other inconsistencies could arise.

I have thought of a solution, which I am leaving here as a note to self:

- [ ] While holding a Declaration of War, a name command could be used, to enter a name which would then be applied to the War object on creation, via the Declaration of War object.
