### ISSUE TITLE
Problem with elevators on signs

### ISSUE THREAD

**Issue by w1th0utme** [TownyAdvanced/Towny#7304]
### What steps will reproduce the problem?

I use the CMI plugin to create elevators and lately for some reason in order to use the elevator players must have permission in the chunk - `/plot set perm destroy on`. To move on elevator up the player must right click on the sign. And to go down, player must press SHIFT and also right click on the sign.

### What is the expected output?

-

### Towny version

0.100.1.18

### Server version

1.20.4

### Please use Pastebin.com to link the following files

-

**Comment by Warriorrrr** [comment]
Towny prevents players from opening up and editing signs in areas they don't have permission for, which is likely what you are seeing here. Whatever method cmi uses to detect the sign being clicked is likely too late as we cancel it [here](https://github.com/TownyAdvanced/Towny/blob/master/Towny/src/main/java/com/palmergames/bukkit/towny/listeners/TownyPaperEvents.java#L198), since I don't own a copy of cmi this is not something I'd feel like looking into at least

**Comment by LlmDl** [comment]
I plan on taking a deeper look into this. I had a initial glance at both plugins and I think it did look like Towny might be able to find a new way around this.

**Comment by LlmDl** [comment]
Fixed by https://github.com/TownyAdvanced/Towny/commit/15253d8697c7d558d7fd2d7b7cea002bfb5507b3
